package config_template

const (
	DANMU_GATEWAY_HERTZ_LISTENADDR     = "hertz.listenaddr"
	DANMU_GATEWAY_HERTZ_LISTENPORT     = "hertz.listenport"
	DANMU_GATEWAY_HERTZ_MONITORINGPORT = "hertz.monitoringport"
	DANMU_GATEWAY_ETCD_SERVICENAME     = "etcd.servicename"
	DANMU_GATEWAY_ETCD_NAMESPACE       = "etcd.namespace"
	DANMU_GATEWAY_POD_UID              = "poduid"

	DANMU_RPC_ETCD_SERVICENAME  = "etcd.servicename"
	DANMU_RPC_ETCD_NAMESPACE    = "etcd.namespace"
	DANMU_RPC_KAFKA_SERVICENAME = "kafka.servicename"
	DANMU_RPC_KAFKA_NAMESPACE   = "kafka.namespace"
	DANMU_RPC_PGSQL_SERVICENAME = "pgsql.servicename"
	DANMU_RPC_PGSQL_NAMESPACE   = "pgsql.namespace"
	DANMU_RPC_PGSQL_USER        = "pgsql.user"
	DANMU_RPC_PGSQL_PASSWORD    = "pgsql.password"
	DANMU_RPC_PGSQL_DBNAME      = "pgsql.dbname"
	DANMU_RPC_REDIS_SERVICENAME = "redis.servicename"
	DANMU_RPC_REDIS_NAMESPACE   = "redis.namespace"
	DANMU_RPC_REDIS_PASSWORD    = "redis.password"
	DANMU_RPC_POD_UID           = "poduid"

	LIVE_DANMU_CONSUMER_KAFKA_SERVICENAME = "kafka.servicename"
	LIVE_DANMU_CONSUMER_KAFKA_NAMESPACE   = "kafka.namespace"
	LIVE_DANMU_CONSUMER_PGSQL_SERVICENAME = "pgsql.servicename"
	LIVE_DANMU_CONSUMER_PGSQL_NAMESPACE   = "pgsql.namespace"
	LIVE_DANMU_CONSUMER_PGSQL_USER        = "pgsql.user"
	LIVE_DANMU_CONSUMER_PGSQL_PASSWORD    = "pgsql.password"
	LIVE_DANMU_CONSUMER_PGSQL_DBNAME      = "pgsql.dbname"
	LIVE_DANMU_CONSUMER_GROUPID           = "groupid"
	LIVE_DANMU_CONSUMER_POD_UID           = "poduid"

	VIDEO_DANMU_CONSUMER_KAFKA_SERVICENAME = "kafka.servicename"
	VIDEO_DANMU_CONSUMER_KAFKA_NAMESPACE   = "kafka.namespace"
	VIDEO_DANMU_CONSUMER_PGSQL_SERVICENAME = "pgsql.servicename"
	VIDEO_DANMU_CONSUMER_PGSQL_NAMESPACE   = "pgsql.namespace"
	VIDEO_DANMU_CONSUMER_PGSQL_USER        = "pgsql.user"
	VIDEO_DANMU_CONSUMER_PGSQL_PASSWORD    = "pgsql.password"
	VIDEO_DANMU_CONSUMER_PGSQL_DBNAME      = "pgsql.dbname"
	VIDEO_DANMU_CONSUMER_REDIS_SERVICENAME = "redis.servicename"
	VIDEO_DANMU_CONSUMER_REDIS_NAMESPACE   = "redis.namespace"
	VIDEO_DANMU_CONSUMER_REDIS_PASSWORD    = "redis.password"
	VIEDO_DANMU_CONSUMER_GROUPID           = "groupid"
	VIDEO_DANMU_CONSUMER_POD_UID           = "poduid"
)
