// Code generated by Kitex v0.15.4. DO NOT EDIT.

package usersvr

import (
	usersvr "LiveDanmu/apps/rpc/usersvr/kitex_gen/usersvr"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	UserLogin(ctx context.Context, req *usersvr.LoginReq, callOptions ...callopt.Option) (r *usersvr.LoginResp, err error)
	RefreshToken(ctx context.Context, req *usersvr.RefreshReq, callOptions ...callopt.Option) (r *usersvr.RefreshResp, err error)
	GetUserInfo(ctx context.Context, req *usersvr.GetUserInfoReq, callOptions ...callopt.Option) (r *usersvr.GetUserInfoResp, err error)
	SetAdminRole(ctx context.Context, req *usersvr.SetAdminRoleReq, callOptions ...callopt.Option) (r *usersvr.SetAdminRoleResp, err error)
	GetAdminer(ctx context.Context, callOptions ...callopt.Option) (r *usersvr.GetAdminerResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserSvrClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserSvrClient struct {
	*kClient
}

func (p *kUserSvrClient) UserLogin(ctx context.Context, req *usersvr.LoginReq, callOptions ...callopt.Option) (r *usersvr.LoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserLogin(ctx, req)
}

func (p *kUserSvrClient) RefreshToken(ctx context.Context, req *usersvr.RefreshReq, callOptions ...callopt.Option) (r *usersvr.RefreshResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RefreshToken(ctx, req)
}

func (p *kUserSvrClient) GetUserInfo(ctx context.Context, req *usersvr.GetUserInfoReq, callOptions ...callopt.Option) (r *usersvr.GetUserInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserInfo(ctx, req)
}

func (p *kUserSvrClient) SetAdminRole(ctx context.Context, req *usersvr.SetAdminRoleReq, callOptions ...callopt.Option) (r *usersvr.SetAdminRoleResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SetAdminRole(ctx, req)
}

func (p *kUserSvrClient) GetAdminer(ctx context.Context, callOptions ...callopt.Option) (r *usersvr.GetAdminerResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetAdminer(ctx)
}
