// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package danmusvr

import (
	"context"
	"fmt"
)

type PubDanmuData struct {
	DanId     int64  `thrift:"dan_id,1,required" frugal:"1,required,i64" json:"dan_id"`
	Rvid      int64  `thrift:"rvid,2,required" frugal:"2,required,i64" json:"rvid"`
	Uid       int64  `thrift:"uid,3,required" frugal:"3,required,i64" json:"uid"`
	Content   string `thrift:"content,4,required" frugal:"4,required,string" json:"content"`
	Color     string `thrift:"color,5,required" frugal:"5,required,string" json:"color"`
	TimeStamp int64  `thrift:"time_stamp,6,required" frugal:"6,required,i64" json:"time_stamp"`
}

func NewPubDanmuData() *PubDanmuData {
	return &PubDanmuData{}
}

func (p *PubDanmuData) InitDefault() {
}

func (p *PubDanmuData) GetDanId() (v int64) {
	return p.DanId
}

func (p *PubDanmuData) GetRvid() (v int64) {
	return p.Rvid
}

func (p *PubDanmuData) GetUid() (v int64) {
	return p.Uid
}

func (p *PubDanmuData) GetContent() (v string) {
	return p.Content
}

func (p *PubDanmuData) GetColor() (v string) {
	return p.Color
}

func (p *PubDanmuData) GetTimeStamp() (v int64) {
	return p.TimeStamp
}
func (p *PubDanmuData) SetDanId(val int64) {
	p.DanId = val
}
func (p *PubDanmuData) SetRvid(val int64) {
	p.Rvid = val
}
func (p *PubDanmuData) SetUid(val int64) {
	p.Uid = val
}
func (p *PubDanmuData) SetContent(val string) {
	p.Content = val
}
func (p *PubDanmuData) SetColor(val string) {
	p.Color = val
}
func (p *PubDanmuData) SetTimeStamp(val int64) {
	p.TimeStamp = val
}

func (p *PubDanmuData) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PubDanmuData(%+v)", *p)
}

var fieldIDToName_PubDanmuData = map[int16]string{
	1: "dan_id",
	2: "rvid",
	3: "uid",
	4: "content",
	5: "color",
	6: "time_stamp",
}

type GetDanmuData struct {
	DanId     int64     `thrift:"dan_id,1,required" frugal:"1,required,i64" json:"dan_id"`
	Rvid      int64     `thrift:"rvid,2,required" frugal:"2,required,i64" json:"rvid"`
	Content   string    `thrift:"content,3,required" frugal:"3,required,string" json:"content"`
	Color     string    `thrift:"color,4,required" frugal:"4,required,string" json:"color"`
	TimeStamp int64     `thrift:"time_stamp,5,required" frugal:"5,required,i64" json:"time_stamp"`
	UserInfo  *UserInfo `thrift:"user_info,6,required" frugal:"6,required,UserInfo" json:"user_info"`
}

func NewGetDanmuData() *GetDanmuData {
	return &GetDanmuData{}
}

func (p *GetDanmuData) InitDefault() {
}

func (p *GetDanmuData) GetDanId() (v int64) {
	return p.DanId
}

func (p *GetDanmuData) GetRvid() (v int64) {
	return p.Rvid
}

func (p *GetDanmuData) GetContent() (v string) {
	return p.Content
}

func (p *GetDanmuData) GetColor() (v string) {
	return p.Color
}

func (p *GetDanmuData) GetTimeStamp() (v int64) {
	return p.TimeStamp
}

var GetDanmuData_UserInfo_DEFAULT *UserInfo

func (p *GetDanmuData) GetUserInfo() (v *UserInfo) {
	if !p.IsSetUserInfo() {
		return GetDanmuData_UserInfo_DEFAULT
	}
	return p.UserInfo
}
func (p *GetDanmuData) SetDanId(val int64) {
	p.DanId = val
}
func (p *GetDanmuData) SetRvid(val int64) {
	p.Rvid = val
}
func (p *GetDanmuData) SetContent(val string) {
	p.Content = val
}
func (p *GetDanmuData) SetColor(val string) {
	p.Color = val
}
func (p *GetDanmuData) SetTimeStamp(val int64) {
	p.TimeStamp = val
}
func (p *GetDanmuData) SetUserInfo(val *UserInfo) {
	p.UserInfo = val
}

func (p *GetDanmuData) IsSetUserInfo() bool {
	return p.UserInfo != nil
}

func (p *GetDanmuData) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetDanmuData(%+v)", *p)
}

var fieldIDToName_GetDanmuData = map[int16]string{
	1: "dan_id",
	2: "rvid",
	3: "content",
	4: "color",
	5: "time_stamp",
	6: "user_info",
}

type UserInfo struct {
	Uid       int64  `thrift:"uid,1,required" frugal:"1,required,i64" json:"uid"`
	UserName  string `thrift:"user_name,2,required" frugal:"2,required,string" json:"user_name"`
	AvatarUrl string `thrift:"avatar_url,3,required" frugal:"3,required,string" json:"avatar_url"`
}

func NewUserInfo() *UserInfo {
	return &UserInfo{}
}

func (p *UserInfo) InitDefault() {
}

func (p *UserInfo) GetUid() (v int64) {
	return p.Uid
}

func (p *UserInfo) GetUserName() (v string) {
	return p.UserName
}

func (p *UserInfo) GetAvatarUrl() (v string) {
	return p.AvatarUrl
}
func (p *UserInfo) SetUid(val int64) {
	p.Uid = val
}
func (p *UserInfo) SetUserName(val string) {
	p.UserName = val
}
func (p *UserInfo) SetAvatarUrl(val string) {
	p.AvatarUrl = val
}

func (p *UserInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserInfo(%+v)", *p)
}

var fieldIDToName_UserInfo = map[int16]string{
	1: "uid",
	2: "user_name",
	3: "avatar_url",
}

type PubVideoResp struct {
	Status int64  `thrift:"status,1,required" frugal:"1,required,i64" json:"status"`
	Info   string `thrift:"info,2,required" frugal:"2,required,string" json:"info"`
}

func NewPubVideoResp() *PubVideoResp {
	return &PubVideoResp{}
}

func (p *PubVideoResp) InitDefault() {
}

func (p *PubVideoResp) GetStatus() (v int64) {
	return p.Status
}

func (p *PubVideoResp) GetInfo() (v string) {
	return p.Info
}
func (p *PubVideoResp) SetStatus(val int64) {
	p.Status = val
}
func (p *PubVideoResp) SetInfo(val string) {
	p.Info = val
}

func (p *PubVideoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PubVideoResp(%+v)", *p)
}

var fieldIDToName_PubVideoResp = map[int16]string{
	1: "status",
	2: "info",
}

type PubVideoReq struct {
	DanmuMsg *PubDanmuData `thrift:"danmuMsg,1,required" frugal:"1,required,PubDanmuData" json:"danmuMsg"`
}

func NewPubVideoReq() *PubVideoReq {
	return &PubVideoReq{}
}

func (p *PubVideoReq) InitDefault() {
}

var PubVideoReq_DanmuMsg_DEFAULT *PubDanmuData

func (p *PubVideoReq) GetDanmuMsg() (v *PubDanmuData) {
	if !p.IsSetDanmuMsg() {
		return PubVideoReq_DanmuMsg_DEFAULT
	}
	return p.DanmuMsg
}
func (p *PubVideoReq) SetDanmuMsg(val *PubDanmuData) {
	p.DanmuMsg = val
}

func (p *PubVideoReq) IsSetDanmuMsg() bool {
	return p.DanmuMsg != nil
}

func (p *PubVideoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PubVideoReq(%+v)", *p)
}

var fieldIDToName_PubVideoReq = map[int16]string{
	1: "danmuMsg",
}

type GetFullResp struct {
	Status int64           `thrift:"status,1,required" frugal:"1,required,i64" json:"status"`
	Info   string          `thrift:"info,2,required" frugal:"2,required,string" json:"info"`
	Data   []*GetDanmuData `thrift:"data,3,required" frugal:"3,required,list<GetDanmuData>" json:"data"`
}

func NewGetFullResp() *GetFullResp {
	return &GetFullResp{}
}

func (p *GetFullResp) InitDefault() {
}

func (p *GetFullResp) GetStatus() (v int64) {
	return p.Status
}

func (p *GetFullResp) GetInfo() (v string) {
	return p.Info
}

func (p *GetFullResp) GetData() (v []*GetDanmuData) {
	return p.Data
}
func (p *GetFullResp) SetStatus(val int64) {
	p.Status = val
}
func (p *GetFullResp) SetInfo(val string) {
	p.Info = val
}
func (p *GetFullResp) SetData(val []*GetDanmuData) {
	p.Data = val
}

func (p *GetFullResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetFullResp(%+v)", *p)
}

var fieldIDToName_GetFullResp = map[int16]string{
	1: "status",
	2: "info",
	3: "data",
}

type GetFullReq struct {
	Rvid int64 `thrift:"rvid,1,required" frugal:"1,required,i64" json:"rvid"`
}

func NewGetFullReq() *GetFullReq {
	return &GetFullReq{}
}

func (p *GetFullReq) InitDefault() {
}

func (p *GetFullReq) GetRvid() (v int64) {
	return p.Rvid
}
func (p *GetFullReq) SetRvid(val int64) {
	p.Rvid = val
}

func (p *GetFullReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetFullReq(%+v)", *p)
}

var fieldIDToName_GetFullReq = map[int16]string{
	1: "rvid",
}

type GetTopResp struct {
	Status int64           `thrift:"status,1,required" frugal:"1,required,i64" json:"status"`
	Info   string          `thrift:"info,2,required" frugal:"2,required,string" json:"info"`
	Data   []*GetDanmuData `thrift:"data,3,required" frugal:"3,required,list<GetDanmuData>" json:"data"`
}

func NewGetTopResp() *GetTopResp {
	return &GetTopResp{}
}

func (p *GetTopResp) InitDefault() {
}

func (p *GetTopResp) GetStatus() (v int64) {
	return p.Status
}

func (p *GetTopResp) GetInfo() (v string) {
	return p.Info
}

func (p *GetTopResp) GetData() (v []*GetDanmuData) {
	return p.Data
}
func (p *GetTopResp) SetStatus(val int64) {
	p.Status = val
}
func (p *GetTopResp) SetInfo(val string) {
	p.Info = val
}
func (p *GetTopResp) SetData(val []*GetDanmuData) {
	p.Data = val
}

func (p *GetTopResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetTopResp(%+v)", *p)
}

var fieldIDToName_GetTopResp = map[int16]string{
	1: "status",
	2: "info",
	3: "data",
}

type GetTopReq struct {
	Rvid int64 `thrift:"rvid,1,required" frugal:"1,required,i64" json:"rvid"`
}

func NewGetTopReq() *GetTopReq {
	return &GetTopReq{}
}

func (p *GetTopReq) InitDefault() {
}

func (p *GetTopReq) GetRvid() (v int64) {
	return p.Rvid
}
func (p *GetTopReq) SetRvid(val int64) {
	p.Rvid = val
}

func (p *GetTopReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetTopReq(%+v)", *p)
}

var fieldIDToName_GetTopReq = map[int16]string{
	1: "rvid",
}

type PubLiveResp struct {
	Status int64  `thrift:"status,1,required" frugal:"1,required,i64" json:"status"`
	Info   string `thrift:"info,2,required" frugal:"2,required,string" json:"info"`
}

func NewPubLiveResp() *PubLiveResp {
	return &PubLiveResp{}
}

func (p *PubLiveResp) InitDefault() {
}

func (p *PubLiveResp) GetStatus() (v int64) {
	return p.Status
}

func (p *PubLiveResp) GetInfo() (v string) {
	return p.Info
}
func (p *PubLiveResp) SetStatus(val int64) {
	p.Status = val
}
func (p *PubLiveResp) SetInfo(val string) {
	p.Info = val
}

func (p *PubLiveResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PubLiveResp(%+v)", *p)
}

var fieldIDToName_PubLiveResp = map[int16]string{
	1: "status",
	2: "info",
}

type PubLiveReq struct {
	DanmuMsg *PubDanmuData `thrift:"danmuMsg,1,required" frugal:"1,required,PubDanmuData" json:"danmuMsg"`
}

func NewPubLiveReq() *PubLiveReq {
	return &PubLiveReq{}
}

func (p *PubLiveReq) InitDefault() {
}

var PubLiveReq_DanmuMsg_DEFAULT *PubDanmuData

func (p *PubLiveReq) GetDanmuMsg() (v *PubDanmuData) {
	if !p.IsSetDanmuMsg() {
		return PubLiveReq_DanmuMsg_DEFAULT
	}
	return p.DanmuMsg
}
func (p *PubLiveReq) SetDanmuMsg(val *PubDanmuData) {
	p.DanmuMsg = val
}

func (p *PubLiveReq) IsSetDanmuMsg() bool {
	return p.DanmuMsg != nil
}

func (p *PubLiveReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PubLiveReq(%+v)", *p)
}

var fieldIDToName_PubLiveReq = map[int16]string{
	1: "danmuMsg",
}

type DelLiveResp struct {
	Status int64  `thrift:"status,1,required" frugal:"1,required,i64" json:"status"`
	Info   string `thrift:"info,2,required" frugal:"2,required,string" json:"info"`
}

func NewDelLiveResp() *DelLiveResp {
	return &DelLiveResp{}
}

func (p *DelLiveResp) InitDefault() {
}

func (p *DelLiveResp) GetStatus() (v int64) {
	return p.Status
}

func (p *DelLiveResp) GetInfo() (v string) {
	return p.Info
}
func (p *DelLiveResp) SetStatus(val int64) {
	p.Status = val
}
func (p *DelLiveResp) SetInfo(val string) {
	p.Info = val
}

func (p *DelLiveResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DelLiveResp(%+v)", *p)
}

var fieldIDToName_DelLiveResp = map[int16]string{
	1: "status",
	2: "info",
}

type DelLiveReq struct {
	DanId int64 `thrift:"dan_id,1,required" frugal:"1,required,i64" json:"dan_id"`
}

func NewDelLiveReq() *DelLiveReq {
	return &DelLiveReq{}
}

func (p *DelLiveReq) InitDefault() {
}

func (p *DelLiveReq) GetDanId() (v int64) {
	return p.DanId
}
func (p *DelLiveReq) SetDanId(val int64) {
	p.DanId = val
}

func (p *DelLiveReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DelLiveReq(%+v)", *p)
}

var fieldIDToName_DelLiveReq = map[int16]string{
	1: "dan_id",
}

type DelResp struct {
	Status int64  `thrift:"status,1,required" frugal:"1,required,i64" json:"status"`
	Info   string `thrift:"info,2,required" frugal:"2,required,string" json:"info"`
}

func NewDelResp() *DelResp {
	return &DelResp{}
}

func (p *DelResp) InitDefault() {
}

func (p *DelResp) GetStatus() (v int64) {
	return p.Status
}

func (p *DelResp) GetInfo() (v string) {
	return p.Info
}
func (p *DelResp) SetStatus(val int64) {
	p.Status = val
}
func (p *DelResp) SetInfo(val string) {
	p.Info = val
}

func (p *DelResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DelResp(%+v)", *p)
}

var fieldIDToName_DelResp = map[int16]string{
	1: "status",
	2: "info",
}

type DelReq struct {
	DanId int64 `thrift:"dan_id,1,required" frugal:"1,required,i64" json:"dan_id"`
	Uid   int64 `thrift:"uid,2,required" frugal:"2,required,i64" json:"uid"`
}

func NewDelReq() *DelReq {
	return &DelReq{}
}

func (p *DelReq) InitDefault() {
}

func (p *DelReq) GetDanId() (v int64) {
	return p.DanId
}

func (p *DelReq) GetUid() (v int64) {
	return p.Uid
}
func (p *DelReq) SetDanId(val int64) {
	p.DanId = val
}
func (p *DelReq) SetUid(val int64) {
	p.Uid = val
}

func (p *DelReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DelReq(%+v)", *p)
}

var fieldIDToName_DelReq = map[int16]string{
	1: "dan_id",
	2: "uid",
}

type DanmuSvr interface {
	PubVideoDanmu(ctx context.Context, req *PubVideoReq) (r *PubVideoResp, err error)

	PubLiveDanmu(ctx context.Context, req *PubLiveReq) (r *PubLiveResp, err error)

	GetDanmu(ctx context.Context, req *GetFullReq) (r *GetFullResp, err error)

	GetTop(ctx context.Context, req *GetTopReq) (r *GetTopResp, err error)

	DelLiveDanmu(ctx context.Context, req *DelLiveReq) (r *DelLiveResp, err error)

	DelDanmu(ctx context.Context, req *DelReq) (r *DelResp, err error)
}

type DanmuSvrPubVideoDanmuArgs struct {
	Req *PubVideoReq `thrift:"req,1" frugal:"1,default,PubVideoReq" json:"req"`
}

func NewDanmuSvrPubVideoDanmuArgs() *DanmuSvrPubVideoDanmuArgs {
	return &DanmuSvrPubVideoDanmuArgs{}
}

func (p *DanmuSvrPubVideoDanmuArgs) InitDefault() {
}

var DanmuSvrPubVideoDanmuArgs_Req_DEFAULT *PubVideoReq

func (p *DanmuSvrPubVideoDanmuArgs) GetReq() (v *PubVideoReq) {
	if !p.IsSetReq() {
		return DanmuSvrPubVideoDanmuArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DanmuSvrPubVideoDanmuArgs) SetReq(val *PubVideoReq) {
	p.Req = val
}

func (p *DanmuSvrPubVideoDanmuArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DanmuSvrPubVideoDanmuArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DanmuSvrPubVideoDanmuArgs(%+v)", *p)
}

var fieldIDToName_DanmuSvrPubVideoDanmuArgs = map[int16]string{
	1: "req",
}

type DanmuSvrPubVideoDanmuResult struct {
	Success *PubVideoResp `thrift:"success,0,optional" frugal:"0,optional,PubVideoResp" json:"success,omitempty"`
}

func NewDanmuSvrPubVideoDanmuResult() *DanmuSvrPubVideoDanmuResult {
	return &DanmuSvrPubVideoDanmuResult{}
}

func (p *DanmuSvrPubVideoDanmuResult) InitDefault() {
}

var DanmuSvrPubVideoDanmuResult_Success_DEFAULT *PubVideoResp

func (p *DanmuSvrPubVideoDanmuResult) GetSuccess() (v *PubVideoResp) {
	if !p.IsSetSuccess() {
		return DanmuSvrPubVideoDanmuResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DanmuSvrPubVideoDanmuResult) SetSuccess(x interface{}) {
	p.Success = x.(*PubVideoResp)
}

func (p *DanmuSvrPubVideoDanmuResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DanmuSvrPubVideoDanmuResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DanmuSvrPubVideoDanmuResult(%+v)", *p)
}

var fieldIDToName_DanmuSvrPubVideoDanmuResult = map[int16]string{
	0: "success",
}

type DanmuSvrPubLiveDanmuArgs struct {
	Req *PubLiveReq `thrift:"req,1" frugal:"1,default,PubLiveReq" json:"req"`
}

func NewDanmuSvrPubLiveDanmuArgs() *DanmuSvrPubLiveDanmuArgs {
	return &DanmuSvrPubLiveDanmuArgs{}
}

func (p *DanmuSvrPubLiveDanmuArgs) InitDefault() {
}

var DanmuSvrPubLiveDanmuArgs_Req_DEFAULT *PubLiveReq

func (p *DanmuSvrPubLiveDanmuArgs) GetReq() (v *PubLiveReq) {
	if !p.IsSetReq() {
		return DanmuSvrPubLiveDanmuArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DanmuSvrPubLiveDanmuArgs) SetReq(val *PubLiveReq) {
	p.Req = val
}

func (p *DanmuSvrPubLiveDanmuArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DanmuSvrPubLiveDanmuArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DanmuSvrPubLiveDanmuArgs(%+v)", *p)
}

var fieldIDToName_DanmuSvrPubLiveDanmuArgs = map[int16]string{
	1: "req",
}

type DanmuSvrPubLiveDanmuResult struct {
	Success *PubLiveResp `thrift:"success,0,optional" frugal:"0,optional,PubLiveResp" json:"success,omitempty"`
}

func NewDanmuSvrPubLiveDanmuResult() *DanmuSvrPubLiveDanmuResult {
	return &DanmuSvrPubLiveDanmuResult{}
}

func (p *DanmuSvrPubLiveDanmuResult) InitDefault() {
}

var DanmuSvrPubLiveDanmuResult_Success_DEFAULT *PubLiveResp

func (p *DanmuSvrPubLiveDanmuResult) GetSuccess() (v *PubLiveResp) {
	if !p.IsSetSuccess() {
		return DanmuSvrPubLiveDanmuResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DanmuSvrPubLiveDanmuResult) SetSuccess(x interface{}) {
	p.Success = x.(*PubLiveResp)
}

func (p *DanmuSvrPubLiveDanmuResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DanmuSvrPubLiveDanmuResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DanmuSvrPubLiveDanmuResult(%+v)", *p)
}

var fieldIDToName_DanmuSvrPubLiveDanmuResult = map[int16]string{
	0: "success",
}

type DanmuSvrGetDanmuArgs struct {
	Req *GetFullReq `thrift:"req,1" frugal:"1,default,GetFullReq" json:"req"`
}

func NewDanmuSvrGetDanmuArgs() *DanmuSvrGetDanmuArgs {
	return &DanmuSvrGetDanmuArgs{}
}

func (p *DanmuSvrGetDanmuArgs) InitDefault() {
}

var DanmuSvrGetDanmuArgs_Req_DEFAULT *GetFullReq

func (p *DanmuSvrGetDanmuArgs) GetReq() (v *GetFullReq) {
	if !p.IsSetReq() {
		return DanmuSvrGetDanmuArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DanmuSvrGetDanmuArgs) SetReq(val *GetFullReq) {
	p.Req = val
}

func (p *DanmuSvrGetDanmuArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DanmuSvrGetDanmuArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DanmuSvrGetDanmuArgs(%+v)", *p)
}

var fieldIDToName_DanmuSvrGetDanmuArgs = map[int16]string{
	1: "req",
}

type DanmuSvrGetDanmuResult struct {
	Success *GetFullResp `thrift:"success,0,optional" frugal:"0,optional,GetFullResp" json:"success,omitempty"`
}

func NewDanmuSvrGetDanmuResult() *DanmuSvrGetDanmuResult {
	return &DanmuSvrGetDanmuResult{}
}

func (p *DanmuSvrGetDanmuResult) InitDefault() {
}

var DanmuSvrGetDanmuResult_Success_DEFAULT *GetFullResp

func (p *DanmuSvrGetDanmuResult) GetSuccess() (v *GetFullResp) {
	if !p.IsSetSuccess() {
		return DanmuSvrGetDanmuResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DanmuSvrGetDanmuResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetFullResp)
}

func (p *DanmuSvrGetDanmuResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DanmuSvrGetDanmuResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DanmuSvrGetDanmuResult(%+v)", *p)
}

var fieldIDToName_DanmuSvrGetDanmuResult = map[int16]string{
	0: "success",
}

type DanmuSvrGetTopArgs struct {
	Req *GetTopReq `thrift:"req,1" frugal:"1,default,GetTopReq" json:"req"`
}

func NewDanmuSvrGetTopArgs() *DanmuSvrGetTopArgs {
	return &DanmuSvrGetTopArgs{}
}

func (p *DanmuSvrGetTopArgs) InitDefault() {
}

var DanmuSvrGetTopArgs_Req_DEFAULT *GetTopReq

func (p *DanmuSvrGetTopArgs) GetReq() (v *GetTopReq) {
	if !p.IsSetReq() {
		return DanmuSvrGetTopArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DanmuSvrGetTopArgs) SetReq(val *GetTopReq) {
	p.Req = val
}

func (p *DanmuSvrGetTopArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DanmuSvrGetTopArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DanmuSvrGetTopArgs(%+v)", *p)
}

var fieldIDToName_DanmuSvrGetTopArgs = map[int16]string{
	1: "req",
}

type DanmuSvrGetTopResult struct {
	Success *GetTopResp `thrift:"success,0,optional" frugal:"0,optional,GetTopResp" json:"success,omitempty"`
}

func NewDanmuSvrGetTopResult() *DanmuSvrGetTopResult {
	return &DanmuSvrGetTopResult{}
}

func (p *DanmuSvrGetTopResult) InitDefault() {
}

var DanmuSvrGetTopResult_Success_DEFAULT *GetTopResp

func (p *DanmuSvrGetTopResult) GetSuccess() (v *GetTopResp) {
	if !p.IsSetSuccess() {
		return DanmuSvrGetTopResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DanmuSvrGetTopResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetTopResp)
}

func (p *DanmuSvrGetTopResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DanmuSvrGetTopResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DanmuSvrGetTopResult(%+v)", *p)
}

var fieldIDToName_DanmuSvrGetTopResult = map[int16]string{
	0: "success",
}

type DanmuSvrDelLiveDanmuArgs struct {
	Req *DelLiveReq `thrift:"req,1" frugal:"1,default,DelLiveReq" json:"req"`
}

func NewDanmuSvrDelLiveDanmuArgs() *DanmuSvrDelLiveDanmuArgs {
	return &DanmuSvrDelLiveDanmuArgs{}
}

func (p *DanmuSvrDelLiveDanmuArgs) InitDefault() {
}

var DanmuSvrDelLiveDanmuArgs_Req_DEFAULT *DelLiveReq

func (p *DanmuSvrDelLiveDanmuArgs) GetReq() (v *DelLiveReq) {
	if !p.IsSetReq() {
		return DanmuSvrDelLiveDanmuArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DanmuSvrDelLiveDanmuArgs) SetReq(val *DelLiveReq) {
	p.Req = val
}

func (p *DanmuSvrDelLiveDanmuArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DanmuSvrDelLiveDanmuArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DanmuSvrDelLiveDanmuArgs(%+v)", *p)
}

var fieldIDToName_DanmuSvrDelLiveDanmuArgs = map[int16]string{
	1: "req",
}

type DanmuSvrDelLiveDanmuResult struct {
	Success *DelLiveResp `thrift:"success,0,optional" frugal:"0,optional,DelLiveResp" json:"success,omitempty"`
}

func NewDanmuSvrDelLiveDanmuResult() *DanmuSvrDelLiveDanmuResult {
	return &DanmuSvrDelLiveDanmuResult{}
}

func (p *DanmuSvrDelLiveDanmuResult) InitDefault() {
}

var DanmuSvrDelLiveDanmuResult_Success_DEFAULT *DelLiveResp

func (p *DanmuSvrDelLiveDanmuResult) GetSuccess() (v *DelLiveResp) {
	if !p.IsSetSuccess() {
		return DanmuSvrDelLiveDanmuResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DanmuSvrDelLiveDanmuResult) SetSuccess(x interface{}) {
	p.Success = x.(*DelLiveResp)
}

func (p *DanmuSvrDelLiveDanmuResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DanmuSvrDelLiveDanmuResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DanmuSvrDelLiveDanmuResult(%+v)", *p)
}

var fieldIDToName_DanmuSvrDelLiveDanmuResult = map[int16]string{
	0: "success",
}

type DanmuSvrDelDanmuArgs struct {
	Req *DelReq `thrift:"req,1" frugal:"1,default,DelReq" json:"req"`
}

func NewDanmuSvrDelDanmuArgs() *DanmuSvrDelDanmuArgs {
	return &DanmuSvrDelDanmuArgs{}
}

func (p *DanmuSvrDelDanmuArgs) InitDefault() {
}

var DanmuSvrDelDanmuArgs_Req_DEFAULT *DelReq

func (p *DanmuSvrDelDanmuArgs) GetReq() (v *DelReq) {
	if !p.IsSetReq() {
		return DanmuSvrDelDanmuArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *DanmuSvrDelDanmuArgs) SetReq(val *DelReq) {
	p.Req = val
}

func (p *DanmuSvrDelDanmuArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DanmuSvrDelDanmuArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DanmuSvrDelDanmuArgs(%+v)", *p)
}

var fieldIDToName_DanmuSvrDelDanmuArgs = map[int16]string{
	1: "req",
}

type DanmuSvrDelDanmuResult struct {
	Success *DelResp `thrift:"success,0,optional" frugal:"0,optional,DelResp" json:"success,omitempty"`
}

func NewDanmuSvrDelDanmuResult() *DanmuSvrDelDanmuResult {
	return &DanmuSvrDelDanmuResult{}
}

func (p *DanmuSvrDelDanmuResult) InitDefault() {
}

var DanmuSvrDelDanmuResult_Success_DEFAULT *DelResp

func (p *DanmuSvrDelDanmuResult) GetSuccess() (v *DelResp) {
	if !p.IsSetSuccess() {
		return DanmuSvrDelDanmuResult_Success_DEFAULT
	}
	return p.Success
}
func (p *DanmuSvrDelDanmuResult) SetSuccess(x interface{}) {
	p.Success = x.(*DelResp)
}

func (p *DanmuSvrDelDanmuResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DanmuSvrDelDanmuResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DanmuSvrDelDanmuResult(%+v)", *p)
}

var fieldIDToName_DanmuSvrDelDanmuResult = map[int16]string{
	0: "success",
}
