// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package pub

import (
	"context"
	"fmt"
)

type DanmuMsg struct {
	RoomId  int64  `thrift:"room_id,1,required" frugal:"1,required,i64" json:"room_id"`
	UserId  int64  `thrift:"user_id,2,required" frugal:"2,required,i64" json:"user_id"`
	Content string `thrift:"content,3,required" frugal:"3,required,string" json:"content"`
	Color   string `thrift:"color,4,required" frugal:"4,required,string" json:"color"`
	Ts      int64  `thrift:"ts,5,required" frugal:"5,required,i64" json:"ts"`
}

func NewDanmuMsg() *DanmuMsg {
	return &DanmuMsg{
		Color: "#FFFFFF",
	}
}

func (p *DanmuMsg) InitDefault() {
	p.Color = "#FFFFFF"
}

func (p *DanmuMsg) GetRoomId() (v int64) {
	return p.RoomId
}

func (p *DanmuMsg) GetUserId() (v int64) {
	return p.UserId
}

func (p *DanmuMsg) GetContent() (v string) {
	return p.Content
}

func (p *DanmuMsg) GetColor() (v string) {
	return p.Color
}

func (p *DanmuMsg) GetTs() (v int64) {
	return p.Ts
}
func (p *DanmuMsg) SetRoomId(val int64) {
	p.RoomId = val
}
func (p *DanmuMsg) SetUserId(val int64) {
	p.UserId = val
}
func (p *DanmuMsg) SetContent(val string) {
	p.Content = val
}
func (p *DanmuMsg) SetColor(val string) {
	p.Color = val
}
func (p *DanmuMsg) SetTs(val int64) {
	p.Ts = val
}

func (p *DanmuMsg) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DanmuMsg(%+v)", *p)
}

var fieldIDToName_DanmuMsg = map[int16]string{
	1: "room_id",
	2: "user_id",
	3: "content",
	4: "color",
	5: "ts",
}

type PubResp struct {
	Status int64  `thrift:"status,1,required" frugal:"1,required,i64" json:"status"`
	Info   string `thrift:"info,2,required" frugal:"2,required,string" json:"info"`
}

func NewPubResp() *PubResp {
	return &PubResp{}
}

func (p *PubResp) InitDefault() {
}

func (p *PubResp) GetStatus() (v int64) {
	return p.Status
}

func (p *PubResp) GetInfo() (v string) {
	return p.Info
}
func (p *PubResp) SetStatus(val int64) {
	p.Status = val
}
func (p *PubResp) SetInfo(val string) {
	p.Info = val
}

func (p *PubResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PubResp(%+v)", *p)
}

var fieldIDToName_PubResp = map[int16]string{
	1: "status",
	2: "info",
}

type PubReq struct {
	DanmuMsg *DanmuMsg `thrift:"danmuMsg,1,required" frugal:"1,required,DanmuMsg" json:"danmuMsg"`
}

func NewPubReq() *PubReq {
	return &PubReq{}
}

func (p *PubReq) InitDefault() {
}

var PubReq_DanmuMsg_DEFAULT *DanmuMsg

func (p *PubReq) GetDanmuMsg() (v *DanmuMsg) {
	if !p.IsSetDanmuMsg() {
		return PubReq_DanmuMsg_DEFAULT
	}
	return p.DanmuMsg
}
func (p *PubReq) SetDanmuMsg(val *DanmuMsg) {
	p.DanmuMsg = val
}

func (p *PubReq) IsSetDanmuMsg() bool {
	return p.DanmuMsg != nil
}

func (p *PubReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PubReq(%+v)", *p)
}

var fieldIDToName_PubReq = map[int16]string{
	1: "danmuMsg",
}

type Pub interface {
	Pub(ctx context.Context, req *PubReq) (r *PubResp, err error)
}

type PubPubArgs struct {
	Req *PubReq `thrift:"req,1" frugal:"1,default,PubReq" json:"req"`
}

func NewPubPubArgs() *PubPubArgs {
	return &PubPubArgs{}
}

func (p *PubPubArgs) InitDefault() {
}

var PubPubArgs_Req_DEFAULT *PubReq

func (p *PubPubArgs) GetReq() (v *PubReq) {
	if !p.IsSetReq() {
		return PubPubArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *PubPubArgs) SetReq(val *PubReq) {
	p.Req = val
}

func (p *PubPubArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PubPubArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PubPubArgs(%+v)", *p)
}

var fieldIDToName_PubPubArgs = map[int16]string{
	1: "req",
}

type PubPubResult struct {
	Success *PubResp `thrift:"success,0,optional" frugal:"0,optional,PubResp" json:"success,omitempty"`
}

func NewPubPubResult() *PubPubResult {
	return &PubPubResult{}
}

func (p *PubPubResult) InitDefault() {
}

var PubPubResult_Success_DEFAULT *PubResp

func (p *PubPubResult) GetSuccess() (v *PubResp) {
	if !p.IsSetSuccess() {
		return PubPubResult_Success_DEFAULT
	}
	return p.Success
}
func (p *PubPubResult) SetSuccess(x interface{}) {
	p.Success = x.(*PubResp)
}

func (p *PubPubResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PubPubResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PubPubResult(%+v)", *p)
}

var fieldIDToName_PubPubResult = map[int16]string{
	0: "success",
}
