// Code generated by Kitex v0.15.4. DO NOT EDIT.

package livesvr

import (
	livesvr "LiveDanmu/apps/rpc/livesvr/kitex_gen/livesvr"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetLiveInfo(ctx context.Context, req *livesvr.GetLiveInfoReq, callOptions ...callopt.Option) (r *livesvr.GetLiveInfoResp, err error)
	GetLiveList(ctx context.Context, callOptions ...callopt.Option) (r *livesvr.GetLiveListResp, err error)
	StartLive(ctx context.Context, req *livesvr.StartLiveReq, callOptions ...callopt.Option) (r *livesvr.StartLiveResp, err error)
	StopLive(ctx context.Context, req *livesvr.StopLiveReq, callOptions ...callopt.Option) (r *livesvr.StopLiveResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kLiveSvrClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kLiveSvrClient struct {
	*kClient
}

func (p *kLiveSvrClient) GetLiveInfo(ctx context.Context, req *livesvr.GetLiveInfoReq, callOptions ...callopt.Option) (r *livesvr.GetLiveInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetLiveInfo(ctx, req)
}

func (p *kLiveSvrClient) GetLiveList(ctx context.Context, callOptions ...callopt.Option) (r *livesvr.GetLiveListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetLiveList(ctx)
}

func (p *kLiveSvrClient) StartLive(ctx context.Context, req *livesvr.StartLiveReq, callOptions ...callopt.Option) (r *livesvr.StartLiveResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.StartLive(ctx, req)
}

func (p *kLiveSvrClient) StopLive(ctx context.Context, req *livesvr.StopLiveReq, callOptions ...callopt.Option) (r *livesvr.StopLiveResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.StopLive(ctx, req)
}
