// Code generated by Kitex v0.15.4. DO NOT EDIT.

package livesvr

import (
	livesvr "LiveDanmu/apps/rpc/livesvr/kitex_gen/livesvr"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetLiveInfo": kitex.NewMethodInfo(
		getLiveInfoHandler,
		newLiveSvrGetLiveInfoArgs,
		newLiveSvrGetLiveInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetLiveList": kitex.NewMethodInfo(
		getLiveListHandler,
		newLiveSvrGetLiveListArgs,
		newLiveSvrGetLiveListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"StartLive": kitex.NewMethodInfo(
		startLiveHandler,
		newLiveSvrStartLiveArgs,
		newLiveSvrStartLiveResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"StopLive": kitex.NewMethodInfo(
		stopLiveHandler,
		newLiveSvrStopLiveArgs,
		newLiveSvrStopLiveResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	liveSvrServiceInfo                = NewServiceInfo()
	liveSvrServiceInfoForClient       = NewServiceInfoForClient()
	liveSvrServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return liveSvrServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return liveSvrServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return liveSvrServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "LiveSvr"
	handlerType := (*livesvr.LiveSvr)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "livesvr",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.4",
		Extra:           extra,
	}
	return svcInfo
}

func getLiveInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*livesvr.LiveSvrGetLiveInfoArgs)
	realResult := result.(*livesvr.LiveSvrGetLiveInfoResult)
	success, err := handler.(livesvr.LiveSvr).GetLiveInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLiveSvrGetLiveInfoArgs() interface{} {
	return livesvr.NewLiveSvrGetLiveInfoArgs()
}

func newLiveSvrGetLiveInfoResult() interface{} {
	return livesvr.NewLiveSvrGetLiveInfoResult()
}

func getLiveListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	_ = arg.(*livesvr.LiveSvrGetLiveListArgs)
	realResult := result.(*livesvr.LiveSvrGetLiveListResult)
	success, err := handler.(livesvr.LiveSvr).GetLiveList(ctx)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLiveSvrGetLiveListArgs() interface{} {
	return livesvr.NewLiveSvrGetLiveListArgs()
}

func newLiveSvrGetLiveListResult() interface{} {
	return livesvr.NewLiveSvrGetLiveListResult()
}

func startLiveHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*livesvr.LiveSvrStartLiveArgs)
	realResult := result.(*livesvr.LiveSvrStartLiveResult)
	success, err := handler.(livesvr.LiveSvr).StartLive(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLiveSvrStartLiveArgs() interface{} {
	return livesvr.NewLiveSvrStartLiveArgs()
}

func newLiveSvrStartLiveResult() interface{} {
	return livesvr.NewLiveSvrStartLiveResult()
}

func stopLiveHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*livesvr.LiveSvrStopLiveArgs)
	realResult := result.(*livesvr.LiveSvrStopLiveResult)
	success, err := handler.(livesvr.LiveSvr).StopLive(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newLiveSvrStopLiveArgs() interface{} {
	return livesvr.NewLiveSvrStopLiveArgs()
}

func newLiveSvrStopLiveResult() interface{} {
	return livesvr.NewLiveSvrStopLiveResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetLiveInfo(ctx context.Context, req *livesvr.GetLiveInfoReq) (r *livesvr.GetLiveInfoResp, err error) {
	var _args livesvr.LiveSvrGetLiveInfoArgs
	_args.Req = req
	var _result livesvr.LiveSvrGetLiveInfoResult
	if err = p.c.Call(ctx, "GetLiveInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetLiveList(ctx context.Context) (r *livesvr.GetLiveListResp, err error) {
	var _args livesvr.LiveSvrGetLiveListArgs
	var _result livesvr.LiveSvrGetLiveListResult
	if err = p.c.Call(ctx, "GetLiveList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) StartLive(ctx context.Context, req *livesvr.StartLiveReq) (r *livesvr.StartLiveResp, err error) {
	var _args livesvr.LiveSvrStartLiveArgs
	_args.Req = req
	var _result livesvr.LiveSvrStartLiveResult
	if err = p.c.Call(ctx, "StartLive", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) StopLive(ctx context.Context, req *livesvr.StopLiveReq) (r *livesvr.StopLiveResp, err error) {
	var _args livesvr.LiveSvrStopLiveArgs
	_args.Req = req
	var _result livesvr.LiveSvrStopLiveResult
	if err = p.c.Call(ctx, "StopLive", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
