// Code generated by Kitex v0.15.4. DO NOT EDIT.

package videosvr

import (
	videosvr "LiveDanmu/apps/rpc/videosvr/kitex_gen/videosvr"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	AddVideo(ctx context.Context, req *videosvr.AddVideoReq, callOptions ...callopt.Option) (r *videosvr.AddVideoResp, err error)
	DelVideo(ctx context.Context, req *videosvr.DelVideoReq, callOptions ...callopt.Option) (r *videosvr.DelVideoResp, err error)
	JudgeAccess(ctx context.Context, req *videosvr.JudgeAccessReq, callOptions ...callopt.Option) (r *videosvr.JudgeAccessResp, err error)
	GetJudgeList(ctx context.Context, req *videosvr.GetJudgeListReq, callOptions ...callopt.Option) (r *videosvr.GetJudgeListResp, err error)
	GetVideoList(ctx context.Context, req *videosvr.GetVideoListReq, callOptions ...callopt.Option) (r *videosvr.GetVideoListResp, err error)
	GetPreSignedUrl(ctx context.Context, req *videosvr.GetPreSignedUrlReq, callOptions ...callopt.Option) (r *videosvr.GetPreSignedUrlResp, err error)
	GetMyVideoList(ctx context.Context, req *videosvr.GetMyVideoListReq, callOptions ...callopt.Option) (r *videosvr.GetMyVideoListResp, err error)
	InnocentViewNum(ctx context.Context, req *videosvr.InnocentViewNumReq, callOptions ...callopt.Option) (r *videosvr.InnocentViewNumResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kVideoSvrClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kVideoSvrClient struct {
	*kClient
}

func (p *kVideoSvrClient) AddVideo(ctx context.Context, req *videosvr.AddVideoReq, callOptions ...callopt.Option) (r *videosvr.AddVideoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddVideo(ctx, req)
}

func (p *kVideoSvrClient) DelVideo(ctx context.Context, req *videosvr.DelVideoReq, callOptions ...callopt.Option) (r *videosvr.DelVideoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DelVideo(ctx, req)
}

func (p *kVideoSvrClient) JudgeAccess(ctx context.Context, req *videosvr.JudgeAccessReq, callOptions ...callopt.Option) (r *videosvr.JudgeAccessResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.JudgeAccess(ctx, req)
}

func (p *kVideoSvrClient) GetJudgeList(ctx context.Context, req *videosvr.GetJudgeListReq, callOptions ...callopt.Option) (r *videosvr.GetJudgeListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetJudgeList(ctx, req)
}

func (p *kVideoSvrClient) GetVideoList(ctx context.Context, req *videosvr.GetVideoListReq, callOptions ...callopt.Option) (r *videosvr.GetVideoListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetVideoList(ctx, req)
}

func (p *kVideoSvrClient) GetPreSignedUrl(ctx context.Context, req *videosvr.GetPreSignedUrlReq, callOptions ...callopt.Option) (r *videosvr.GetPreSignedUrlResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetPreSignedUrl(ctx, req)
}

func (p *kVideoSvrClient) GetMyVideoList(ctx context.Context, req *videosvr.GetMyVideoListReq, callOptions ...callopt.Option) (r *videosvr.GetMyVideoListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetMyVideoList(ctx, req)
}

func (p *kVideoSvrClient) InnocentViewNum(ctx context.Context, req *videosvr.InnocentViewNumReq, callOptions ...callopt.Option) (r *videosvr.InnocentViewNumResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.InnocentViewNum(ctx, req)
}
