// Code generated by Kitex v0.15.4. DO NOT EDIT.

package videosvr

import (
	videosvr "LiveDanmu/apps/rpc/videosvr/kitex_gen/videosvr"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"AddVideo": kitex.NewMethodInfo(
		addVideoHandler,
		newVideoSvrAddVideoArgs,
		newVideoSvrAddVideoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DelVideo": kitex.NewMethodInfo(
		delVideoHandler,
		newVideoSvrDelVideoArgs,
		newVideoSvrDelVideoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"JudgeAccess": kitex.NewMethodInfo(
		judgeAccessHandler,
		newVideoSvrJudgeAccessArgs,
		newVideoSvrJudgeAccessResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetJudgeList": kitex.NewMethodInfo(
		getJudgeListHandler,
		newVideoSvrGetJudgeListArgs,
		newVideoSvrGetJudgeListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetVideoList": kitex.NewMethodInfo(
		getVideoListHandler,
		newVideoSvrGetVideoListArgs,
		newVideoSvrGetVideoListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetPreSignedUrl": kitex.NewMethodInfo(
		getPreSignedUrlHandler,
		newVideoSvrGetPreSignedUrlArgs,
		newVideoSvrGetPreSignedUrlResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetMyVideoList": kitex.NewMethodInfo(
		getMyVideoListHandler,
		newVideoSvrGetMyVideoListArgs,
		newVideoSvrGetMyVideoListResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"InnocentViewNum": kitex.NewMethodInfo(
		innocentViewNumHandler,
		newVideoSvrInnocentViewNumArgs,
		newVideoSvrInnocentViewNumResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetVideoDetail": kitex.NewMethodInfo(
		getVideoDetailHandler,
		newVideoSvrGetVideoDetailArgs,
		newVideoSvrGetVideoDetailResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	videoSvrServiceInfo                = NewServiceInfo()
	videoSvrServiceInfoForClient       = NewServiceInfoForClient()
	videoSvrServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return videoSvrServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return videoSvrServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return videoSvrServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "VideoSvr"
	handlerType := (*videosvr.VideoSvr)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "videosvr",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.4",
		Extra:           extra,
	}
	return svcInfo
}

func addVideoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videosvr.VideoSvrAddVideoArgs)
	realResult := result.(*videosvr.VideoSvrAddVideoResult)
	success, err := handler.(videosvr.VideoSvr).AddVideo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoSvrAddVideoArgs() interface{} {
	return videosvr.NewVideoSvrAddVideoArgs()
}

func newVideoSvrAddVideoResult() interface{} {
	return videosvr.NewVideoSvrAddVideoResult()
}

func delVideoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videosvr.VideoSvrDelVideoArgs)
	realResult := result.(*videosvr.VideoSvrDelVideoResult)
	success, err := handler.(videosvr.VideoSvr).DelVideo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoSvrDelVideoArgs() interface{} {
	return videosvr.NewVideoSvrDelVideoArgs()
}

func newVideoSvrDelVideoResult() interface{} {
	return videosvr.NewVideoSvrDelVideoResult()
}

func judgeAccessHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videosvr.VideoSvrJudgeAccessArgs)
	realResult := result.(*videosvr.VideoSvrJudgeAccessResult)
	success, err := handler.(videosvr.VideoSvr).JudgeAccess(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoSvrJudgeAccessArgs() interface{} {
	return videosvr.NewVideoSvrJudgeAccessArgs()
}

func newVideoSvrJudgeAccessResult() interface{} {
	return videosvr.NewVideoSvrJudgeAccessResult()
}

func getJudgeListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videosvr.VideoSvrGetJudgeListArgs)
	realResult := result.(*videosvr.VideoSvrGetJudgeListResult)
	success, err := handler.(videosvr.VideoSvr).GetJudgeList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoSvrGetJudgeListArgs() interface{} {
	return videosvr.NewVideoSvrGetJudgeListArgs()
}

func newVideoSvrGetJudgeListResult() interface{} {
	return videosvr.NewVideoSvrGetJudgeListResult()
}

func getVideoListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videosvr.VideoSvrGetVideoListArgs)
	realResult := result.(*videosvr.VideoSvrGetVideoListResult)
	success, err := handler.(videosvr.VideoSvr).GetVideoList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoSvrGetVideoListArgs() interface{} {
	return videosvr.NewVideoSvrGetVideoListArgs()
}

func newVideoSvrGetVideoListResult() interface{} {
	return videosvr.NewVideoSvrGetVideoListResult()
}

func getPreSignedUrlHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videosvr.VideoSvrGetPreSignedUrlArgs)
	realResult := result.(*videosvr.VideoSvrGetPreSignedUrlResult)
	success, err := handler.(videosvr.VideoSvr).GetPreSignedUrl(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoSvrGetPreSignedUrlArgs() interface{} {
	return videosvr.NewVideoSvrGetPreSignedUrlArgs()
}

func newVideoSvrGetPreSignedUrlResult() interface{} {
	return videosvr.NewVideoSvrGetPreSignedUrlResult()
}

func getMyVideoListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videosvr.VideoSvrGetMyVideoListArgs)
	realResult := result.(*videosvr.VideoSvrGetMyVideoListResult)
	success, err := handler.(videosvr.VideoSvr).GetMyVideoList(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoSvrGetMyVideoListArgs() interface{} {
	return videosvr.NewVideoSvrGetMyVideoListArgs()
}

func newVideoSvrGetMyVideoListResult() interface{} {
	return videosvr.NewVideoSvrGetMyVideoListResult()
}

func innocentViewNumHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videosvr.VideoSvrInnocentViewNumArgs)
	realResult := result.(*videosvr.VideoSvrInnocentViewNumResult)
	success, err := handler.(videosvr.VideoSvr).InnocentViewNum(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoSvrInnocentViewNumArgs() interface{} {
	return videosvr.NewVideoSvrInnocentViewNumArgs()
}

func newVideoSvrInnocentViewNumResult() interface{} {
	return videosvr.NewVideoSvrInnocentViewNumResult()
}

func getVideoDetailHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*videosvr.VideoSvrGetVideoDetailArgs)
	realResult := result.(*videosvr.VideoSvrGetVideoDetailResult)
	success, err := handler.(videosvr.VideoSvr).GetVideoDetail(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newVideoSvrGetVideoDetailArgs() interface{} {
	return videosvr.NewVideoSvrGetVideoDetailArgs()
}

func newVideoSvrGetVideoDetailResult() interface{} {
	return videosvr.NewVideoSvrGetVideoDetailResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) AddVideo(ctx context.Context, req *videosvr.AddVideoReq) (r *videosvr.AddVideoResp, err error) {
	var _args videosvr.VideoSvrAddVideoArgs
	_args.Req = req
	var _result videosvr.VideoSvrAddVideoResult
	if err = p.c.Call(ctx, "AddVideo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DelVideo(ctx context.Context, req *videosvr.DelVideoReq) (r *videosvr.DelVideoResp, err error) {
	var _args videosvr.VideoSvrDelVideoArgs
	_args.Req = req
	var _result videosvr.VideoSvrDelVideoResult
	if err = p.c.Call(ctx, "DelVideo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) JudgeAccess(ctx context.Context, req *videosvr.JudgeAccessReq) (r *videosvr.JudgeAccessResp, err error) {
	var _args videosvr.VideoSvrJudgeAccessArgs
	_args.Req = req
	var _result videosvr.VideoSvrJudgeAccessResult
	if err = p.c.Call(ctx, "JudgeAccess", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetJudgeList(ctx context.Context, req *videosvr.GetJudgeListReq) (r *videosvr.GetJudgeListResp, err error) {
	var _args videosvr.VideoSvrGetJudgeListArgs
	_args.Req = req
	var _result videosvr.VideoSvrGetJudgeListResult
	if err = p.c.Call(ctx, "GetJudgeList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetVideoList(ctx context.Context, req *videosvr.GetVideoListReq) (r *videosvr.GetVideoListResp, err error) {
	var _args videosvr.VideoSvrGetVideoListArgs
	_args.Req = req
	var _result videosvr.VideoSvrGetVideoListResult
	if err = p.c.Call(ctx, "GetVideoList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetPreSignedUrl(ctx context.Context, req *videosvr.GetPreSignedUrlReq) (r *videosvr.GetPreSignedUrlResp, err error) {
	var _args videosvr.VideoSvrGetPreSignedUrlArgs
	_args.Req = req
	var _result videosvr.VideoSvrGetPreSignedUrlResult
	if err = p.c.Call(ctx, "GetPreSignedUrl", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetMyVideoList(ctx context.Context, req *videosvr.GetMyVideoListReq) (r *videosvr.GetMyVideoListResp, err error) {
	var _args videosvr.VideoSvrGetMyVideoListArgs
	_args.Req = req
	var _result videosvr.VideoSvrGetMyVideoListResult
	if err = p.c.Call(ctx, "GetMyVideoList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) InnocentViewNum(ctx context.Context, req *videosvr.InnocentViewNumReq) (r *videosvr.InnocentViewNumResp, err error) {
	var _args videosvr.VideoSvrInnocentViewNumArgs
	_args.Req = req
	var _result videosvr.VideoSvrInnocentViewNumResult
	if err = p.c.Call(ctx, "InnocentViewNum", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetVideoDetail(ctx context.Context, req *videosvr.GetVideoDetailReq) (r *videosvr.GetVideoDetailResp, err error) {
	var _args videosvr.VideoSvrGetVideoDetailArgs
	_args.Req = req
	var _result videosvr.VideoSvrGetVideoDetailResult
	if err = p.c.Call(ctx, "GetVideoDetail", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
