// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package videosvr

import (
	"context"
	"fmt"
)

type VideoInfo struct {
	Rvid        int64  `thrift:"rvid,1,required" frugal:"1,required,i64" json:"rvid"`
	FaceUrl     string `thrift:"face_url,2,required" frugal:"2,required,string" json:"face_url"`
	MinioKey    string `thrift:"minio_key,3,required" frugal:"3,required,string" json:"minio_key"`
	Title       string `thrift:"title,4,required" frugal:"4,required,string" json:"title"`
	Description string `thrift:"description,5,required" frugal:"5,required,string" json:"description"`
	ViewNum     int64  `thrift:"view_num,6,required" frugal:"6,required,i64" json:"view_num"`
	UseFace     bool   `thrift:"use_face,7,required" frugal:"7,required,bool" json:"use_face"`
	InJudge     bool   `thrift:"in_judge,8,required" frugal:"8,required,bool" json:"in_judge"`
	AuthorId    int64  `thrift:"author_id,9,required" frugal:"9,required,i64" json:"author_id"`
	AuthorName  string `thrift:"author_name,10,required" frugal:"10,required,string" json:"author_name"`
}

func NewVideoInfo() *VideoInfo {
	return &VideoInfo{}
}

func (p *VideoInfo) InitDefault() {
}

func (p *VideoInfo) GetRvid() (v int64) {
	return p.Rvid
}

func (p *VideoInfo) GetFaceUrl() (v string) {
	return p.FaceUrl
}

func (p *VideoInfo) GetMinioKey() (v string) {
	return p.MinioKey
}

func (p *VideoInfo) GetTitle() (v string) {
	return p.Title
}

func (p *VideoInfo) GetDescription() (v string) {
	return p.Description
}

func (p *VideoInfo) GetViewNum() (v int64) {
	return p.ViewNum
}

func (p *VideoInfo) GetUseFace() (v bool) {
	return p.UseFace
}

func (p *VideoInfo) GetInJudge() (v bool) {
	return p.InJudge
}

func (p *VideoInfo) GetAuthorId() (v int64) {
	return p.AuthorId
}

func (p *VideoInfo) GetAuthorName() (v string) {
	return p.AuthorName
}
func (p *VideoInfo) SetRvid(val int64) {
	p.Rvid = val
}
func (p *VideoInfo) SetFaceUrl(val string) {
	p.FaceUrl = val
}
func (p *VideoInfo) SetMinioKey(val string) {
	p.MinioKey = val
}
func (p *VideoInfo) SetTitle(val string) {
	p.Title = val
}
func (p *VideoInfo) SetDescription(val string) {
	p.Description = val
}
func (p *VideoInfo) SetViewNum(val int64) {
	p.ViewNum = val
}
func (p *VideoInfo) SetUseFace(val bool) {
	p.UseFace = val
}
func (p *VideoInfo) SetInJudge(val bool) {
	p.InJudge = val
}
func (p *VideoInfo) SetAuthorId(val int64) {
	p.AuthorId = val
}
func (p *VideoInfo) SetAuthorName(val string) {
	p.AuthorName = val
}

func (p *VideoInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoInfo(%+v)", *p)
}

var fieldIDToName_VideoInfo = map[int16]string{
	1:  "rvid",
	2:  "face_url",
	3:  "minio_key",
	4:  "title",
	5:  "description",
	6:  "view_num",
	7:  "use_face",
	8:  "in_judge",
	9:  "author_id",
	10: "author_name",
}

type AddVideoReq struct {
	VideoInfo *VideoInfo `thrift:"video_info,1,required" frugal:"1,required,VideoInfo" json:"video_info"`
}

func NewAddVideoReq() *AddVideoReq {
	return &AddVideoReq{}
}

func (p *AddVideoReq) InitDefault() {
}

var AddVideoReq_VideoInfo_DEFAULT *VideoInfo

func (p *AddVideoReq) GetVideoInfo() (v *VideoInfo) {
	if !p.IsSetVideoInfo() {
		return AddVideoReq_VideoInfo_DEFAULT
	}
	return p.VideoInfo
}
func (p *AddVideoReq) SetVideoInfo(val *VideoInfo) {
	p.VideoInfo = val
}

func (p *AddVideoReq) IsSetVideoInfo() bool {
	return p.VideoInfo != nil
}

func (p *AddVideoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AddVideoReq(%+v)", *p)
}

var fieldIDToName_AddVideoReq = map[int16]string{
	1: "video_info",
}

type AddVideoResp struct {
	Status int64  `thrift:"status,1,required" frugal:"1,required,i64" json:"status"`
	Info   string `thrift:"info,2,required" frugal:"2,required,string" json:"info"`
}

func NewAddVideoResp() *AddVideoResp {
	return &AddVideoResp{}
}

func (p *AddVideoResp) InitDefault() {
}

func (p *AddVideoResp) GetStatus() (v int64) {
	return p.Status
}

func (p *AddVideoResp) GetInfo() (v string) {
	return p.Info
}
func (p *AddVideoResp) SetStatus(val int64) {
	p.Status = val
}
func (p *AddVideoResp) SetInfo(val string) {
	p.Info = val
}

func (p *AddVideoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AddVideoResp(%+v)", *p)
}

var fieldIDToName_AddVideoResp = map[int16]string{
	1: "status",
	2: "info",
}

type DelVideoReq struct {
	Rvid int64 `thrift:"rvid,1,required" frugal:"1,required,i64" json:"rvid"`
}

func NewDelVideoReq() *DelVideoReq {
	return &DelVideoReq{}
}

func (p *DelVideoReq) InitDefault() {
}

func (p *DelVideoReq) GetRvid() (v int64) {
	return p.Rvid
}
func (p *DelVideoReq) SetRvid(val int64) {
	p.Rvid = val
}

func (p *DelVideoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DelVideoReq(%+v)", *p)
}

var fieldIDToName_DelVideoReq = map[int16]string{
	1: "rvid",
}

type DelVideoResp struct {
	Status int64  `thrift:"status,1,required" frugal:"1,required,i64" json:"status"`
	Info   string `thrift:"info,2,required" frugal:"2,required,string" json:"info"`
}

func NewDelVideoResp() *DelVideoResp {
	return &DelVideoResp{}
}

func (p *DelVideoResp) InitDefault() {
}

func (p *DelVideoResp) GetStatus() (v int64) {
	return p.Status
}

func (p *DelVideoResp) GetInfo() (v string) {
	return p.Info
}
func (p *DelVideoResp) SetStatus(val int64) {
	p.Status = val
}
func (p *DelVideoResp) SetInfo(val string) {
	p.Info = val
}

func (p *DelVideoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DelVideoResp(%+v)", *p)
}

var fieldIDToName_DelVideoResp = map[int16]string{
	1: "status",
	2: "info",
}

type JudgeAccessReq struct {
	Rvid int64 `thrift:"rvid,1,required" frugal:"1,required,i64" json:"rvid"`
}

func NewJudgeAccessReq() *JudgeAccessReq {
	return &JudgeAccessReq{}
}

func (p *JudgeAccessReq) InitDefault() {
}

func (p *JudgeAccessReq) GetRvid() (v int64) {
	return p.Rvid
}
func (p *JudgeAccessReq) SetRvid(val int64) {
	p.Rvid = val
}

func (p *JudgeAccessReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("JudgeAccessReq(%+v)", *p)
}

var fieldIDToName_JudgeAccessReq = map[int16]string{
	1: "rvid",
}

type JudgeAccessResp struct {
	Status int64  `thrift:"status,1,required" frugal:"1,required,i64" json:"status"`
	Info   string `thrift:"info,2,required" frugal:"2,required,string" json:"info"`
}

func NewJudgeAccessResp() *JudgeAccessResp {
	return &JudgeAccessResp{}
}

func (p *JudgeAccessResp) InitDefault() {
}

func (p *JudgeAccessResp) GetStatus() (v int64) {
	return p.Status
}

func (p *JudgeAccessResp) GetInfo() (v string) {
	return p.Info
}
func (p *JudgeAccessResp) SetStatus(val int64) {
	p.Status = val
}
func (p *JudgeAccessResp) SetInfo(val string) {
	p.Info = val
}

func (p *JudgeAccessResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("JudgeAccessResp(%+v)", *p)
}

var fieldIDToName_JudgeAccessResp = map[int16]string{
	1: "status",
	2: "info",
}

type GetVideoListReq struct {
	Page     int32 `thrift:"page,1,required" frugal:"1,required,i32" json:"page"`
	PageSize int32 `thrift:"page_size,2,required" frugal:"2,required,i32" json:"page_size"`
}

func NewGetVideoListReq() *GetVideoListReq {
	return &GetVideoListReq{}
}

func (p *GetVideoListReq) InitDefault() {
}

func (p *GetVideoListReq) GetPage() (v int32) {
	return p.Page
}

func (p *GetVideoListReq) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *GetVideoListReq) SetPage(val int32) {
	p.Page = val
}
func (p *GetVideoListReq) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *GetVideoListReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetVideoListReq(%+v)", *p)
}

var fieldIDToName_GetVideoListReq = map[int16]string{
	1: "page",
	2: "page_size",
}

type GetVideoListResp struct {
	Status int64        `thrift:"status,1,required" frugal:"1,required,i64" json:"status"`
	Info   string       `thrift:"info,2,required" frugal:"2,required,string" json:"info"`
	Data   []*VideoInfo `thrift:"data,3,required" frugal:"3,required,list<VideoInfo>" json:"data"`
}

func NewGetVideoListResp() *GetVideoListResp {
	return &GetVideoListResp{}
}

func (p *GetVideoListResp) InitDefault() {
}

func (p *GetVideoListResp) GetStatus() (v int64) {
	return p.Status
}

func (p *GetVideoListResp) GetInfo() (v string) {
	return p.Info
}

func (p *GetVideoListResp) GetData() (v []*VideoInfo) {
	return p.Data
}
func (p *GetVideoListResp) SetStatus(val int64) {
	p.Status = val
}
func (p *GetVideoListResp) SetInfo(val string) {
	p.Info = val
}
func (p *GetVideoListResp) SetData(val []*VideoInfo) {
	p.Data = val
}

func (p *GetVideoListResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetVideoListResp(%+v)", *p)
}

var fieldIDToName_GetVideoListResp = map[int16]string{
	1: "status",
	2: "info",
	3: "data",
}

type GetPreSignedUrlReq struct {
	Rvid string `thrift:"rvid,1,required" frugal:"1,required,string" json:"rvid"`
	Uid  int64  `thrift:"uid,2,required" frugal:"2,required,i64" json:"uid"`
	Role string `thrift:"role,3,required" frugal:"3,required,string" json:"role"`
}

func NewGetPreSignedUrlReq() *GetPreSignedUrlReq {
	return &GetPreSignedUrlReq{}
}

func (p *GetPreSignedUrlReq) InitDefault() {
}

func (p *GetPreSignedUrlReq) GetRvid() (v string) {
	return p.Rvid
}

func (p *GetPreSignedUrlReq) GetUid() (v int64) {
	return p.Uid
}

func (p *GetPreSignedUrlReq) GetRole() (v string) {
	return p.Role
}
func (p *GetPreSignedUrlReq) SetRvid(val string) {
	p.Rvid = val
}
func (p *GetPreSignedUrlReq) SetUid(val int64) {
	p.Uid = val
}
func (p *GetPreSignedUrlReq) SetRole(val string) {
	p.Role = val
}

func (p *GetPreSignedUrlReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetPreSignedUrlReq(%+v)", *p)
}

var fieldIDToName_GetPreSignedUrlReq = map[int16]string{
	1: "rvid",
	2: "uid",
	3: "role",
}

type GetPreSignedUrlResp struct {
	Status int64  `thrift:"status,1,required" frugal:"1,required,i64" json:"status"`
	Info   string `thrift:"info,2,required" frugal:"2,required,string" json:"info"`
	Data   string `thrift:"data,3,required" frugal:"3,required,string" json:"data"`
}

func NewGetPreSignedUrlResp() *GetPreSignedUrlResp {
	return &GetPreSignedUrlResp{}
}

func (p *GetPreSignedUrlResp) InitDefault() {
}

func (p *GetPreSignedUrlResp) GetStatus() (v int64) {
	return p.Status
}

func (p *GetPreSignedUrlResp) GetInfo() (v string) {
	return p.Info
}

func (p *GetPreSignedUrlResp) GetData() (v string) {
	return p.Data
}
func (p *GetPreSignedUrlResp) SetStatus(val int64) {
	p.Status = val
}
func (p *GetPreSignedUrlResp) SetInfo(val string) {
	p.Info = val
}
func (p *GetPreSignedUrlResp) SetData(val string) {
	p.Data = val
}

func (p *GetPreSignedUrlResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetPreSignedUrlResp(%+v)", *p)
}

var fieldIDToName_GetPreSignedUrlResp = map[int16]string{
	1: "status",
	2: "info",
	3: "data",
}

type VideoSvr interface {
	AddVideo(ctx context.Context, req *AddVideoReq) (r *AddVideoResp, err error)

	DelVideo(ctx context.Context, req *DelVideoReq) (r *DelVideoResp, err error)

	JudgeAccess(ctx context.Context, req *JudgeAccessReq) (r *JudgeAccessResp, err error)

	GetVideoList(ctx context.Context, req *GetPreSignedUrlReq) (r *GetVideoListResp, err error)

	GetPreSignedUrl(ctx context.Context, req *GetPreSignedUrlReq) (r *GetPreSignedUrlResp, err error)
}

type VideoSvrAddVideoArgs struct {
	Req *AddVideoReq `thrift:"req,1" frugal:"1,default,AddVideoReq" json:"req"`
}

func NewVideoSvrAddVideoArgs() *VideoSvrAddVideoArgs {
	return &VideoSvrAddVideoArgs{}
}

func (p *VideoSvrAddVideoArgs) InitDefault() {
}

var VideoSvrAddVideoArgs_Req_DEFAULT *AddVideoReq

func (p *VideoSvrAddVideoArgs) GetReq() (v *AddVideoReq) {
	if !p.IsSetReq() {
		return VideoSvrAddVideoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoSvrAddVideoArgs) SetReq(val *AddVideoReq) {
	p.Req = val
}

func (p *VideoSvrAddVideoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoSvrAddVideoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoSvrAddVideoArgs(%+v)", *p)
}

var fieldIDToName_VideoSvrAddVideoArgs = map[int16]string{
	1: "req",
}

type VideoSvrAddVideoResult struct {
	Success *AddVideoResp `thrift:"success,0,optional" frugal:"0,optional,AddVideoResp" json:"success,omitempty"`
}

func NewVideoSvrAddVideoResult() *VideoSvrAddVideoResult {
	return &VideoSvrAddVideoResult{}
}

func (p *VideoSvrAddVideoResult) InitDefault() {
}

var VideoSvrAddVideoResult_Success_DEFAULT *AddVideoResp

func (p *VideoSvrAddVideoResult) GetSuccess() (v *AddVideoResp) {
	if !p.IsSetSuccess() {
		return VideoSvrAddVideoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoSvrAddVideoResult) SetSuccess(x interface{}) {
	p.Success = x.(*AddVideoResp)
}

func (p *VideoSvrAddVideoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoSvrAddVideoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoSvrAddVideoResult(%+v)", *p)
}

var fieldIDToName_VideoSvrAddVideoResult = map[int16]string{
	0: "success",
}

type VideoSvrDelVideoArgs struct {
	Req *DelVideoReq `thrift:"req,1" frugal:"1,default,DelVideoReq" json:"req"`
}

func NewVideoSvrDelVideoArgs() *VideoSvrDelVideoArgs {
	return &VideoSvrDelVideoArgs{}
}

func (p *VideoSvrDelVideoArgs) InitDefault() {
}

var VideoSvrDelVideoArgs_Req_DEFAULT *DelVideoReq

func (p *VideoSvrDelVideoArgs) GetReq() (v *DelVideoReq) {
	if !p.IsSetReq() {
		return VideoSvrDelVideoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoSvrDelVideoArgs) SetReq(val *DelVideoReq) {
	p.Req = val
}

func (p *VideoSvrDelVideoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoSvrDelVideoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoSvrDelVideoArgs(%+v)", *p)
}

var fieldIDToName_VideoSvrDelVideoArgs = map[int16]string{
	1: "req",
}

type VideoSvrDelVideoResult struct {
	Success *DelVideoResp `thrift:"success,0,optional" frugal:"0,optional,DelVideoResp" json:"success,omitempty"`
}

func NewVideoSvrDelVideoResult() *VideoSvrDelVideoResult {
	return &VideoSvrDelVideoResult{}
}

func (p *VideoSvrDelVideoResult) InitDefault() {
}

var VideoSvrDelVideoResult_Success_DEFAULT *DelVideoResp

func (p *VideoSvrDelVideoResult) GetSuccess() (v *DelVideoResp) {
	if !p.IsSetSuccess() {
		return VideoSvrDelVideoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoSvrDelVideoResult) SetSuccess(x interface{}) {
	p.Success = x.(*DelVideoResp)
}

func (p *VideoSvrDelVideoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoSvrDelVideoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoSvrDelVideoResult(%+v)", *p)
}

var fieldIDToName_VideoSvrDelVideoResult = map[int16]string{
	0: "success",
}

type VideoSvrJudgeAccessArgs struct {
	Req *JudgeAccessReq `thrift:"req,1" frugal:"1,default,JudgeAccessReq" json:"req"`
}

func NewVideoSvrJudgeAccessArgs() *VideoSvrJudgeAccessArgs {
	return &VideoSvrJudgeAccessArgs{}
}

func (p *VideoSvrJudgeAccessArgs) InitDefault() {
}

var VideoSvrJudgeAccessArgs_Req_DEFAULT *JudgeAccessReq

func (p *VideoSvrJudgeAccessArgs) GetReq() (v *JudgeAccessReq) {
	if !p.IsSetReq() {
		return VideoSvrJudgeAccessArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoSvrJudgeAccessArgs) SetReq(val *JudgeAccessReq) {
	p.Req = val
}

func (p *VideoSvrJudgeAccessArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoSvrJudgeAccessArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoSvrJudgeAccessArgs(%+v)", *p)
}

var fieldIDToName_VideoSvrJudgeAccessArgs = map[int16]string{
	1: "req",
}

type VideoSvrJudgeAccessResult struct {
	Success *JudgeAccessResp `thrift:"success,0,optional" frugal:"0,optional,JudgeAccessResp" json:"success,omitempty"`
}

func NewVideoSvrJudgeAccessResult() *VideoSvrJudgeAccessResult {
	return &VideoSvrJudgeAccessResult{}
}

func (p *VideoSvrJudgeAccessResult) InitDefault() {
}

var VideoSvrJudgeAccessResult_Success_DEFAULT *JudgeAccessResp

func (p *VideoSvrJudgeAccessResult) GetSuccess() (v *JudgeAccessResp) {
	if !p.IsSetSuccess() {
		return VideoSvrJudgeAccessResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoSvrJudgeAccessResult) SetSuccess(x interface{}) {
	p.Success = x.(*JudgeAccessResp)
}

func (p *VideoSvrJudgeAccessResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoSvrJudgeAccessResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoSvrJudgeAccessResult(%+v)", *p)
}

var fieldIDToName_VideoSvrJudgeAccessResult = map[int16]string{
	0: "success",
}

type VideoSvrGetVideoListArgs struct {
	Req *GetPreSignedUrlReq `thrift:"req,1" frugal:"1,default,GetPreSignedUrlReq" json:"req"`
}

func NewVideoSvrGetVideoListArgs() *VideoSvrGetVideoListArgs {
	return &VideoSvrGetVideoListArgs{}
}

func (p *VideoSvrGetVideoListArgs) InitDefault() {
}

var VideoSvrGetVideoListArgs_Req_DEFAULT *GetPreSignedUrlReq

func (p *VideoSvrGetVideoListArgs) GetReq() (v *GetPreSignedUrlReq) {
	if !p.IsSetReq() {
		return VideoSvrGetVideoListArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoSvrGetVideoListArgs) SetReq(val *GetPreSignedUrlReq) {
	p.Req = val
}

func (p *VideoSvrGetVideoListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoSvrGetVideoListArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoSvrGetVideoListArgs(%+v)", *p)
}

var fieldIDToName_VideoSvrGetVideoListArgs = map[int16]string{
	1: "req",
}

type VideoSvrGetVideoListResult struct {
	Success *GetVideoListResp `thrift:"success,0,optional" frugal:"0,optional,GetVideoListResp" json:"success,omitempty"`
}

func NewVideoSvrGetVideoListResult() *VideoSvrGetVideoListResult {
	return &VideoSvrGetVideoListResult{}
}

func (p *VideoSvrGetVideoListResult) InitDefault() {
}

var VideoSvrGetVideoListResult_Success_DEFAULT *GetVideoListResp

func (p *VideoSvrGetVideoListResult) GetSuccess() (v *GetVideoListResp) {
	if !p.IsSetSuccess() {
		return VideoSvrGetVideoListResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoSvrGetVideoListResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetVideoListResp)
}

func (p *VideoSvrGetVideoListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoSvrGetVideoListResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoSvrGetVideoListResult(%+v)", *p)
}

var fieldIDToName_VideoSvrGetVideoListResult = map[int16]string{
	0: "success",
}

type VideoSvrGetPreSignedUrlArgs struct {
	Req *GetPreSignedUrlReq `thrift:"req,1" frugal:"1,default,GetPreSignedUrlReq" json:"req"`
}

func NewVideoSvrGetPreSignedUrlArgs() *VideoSvrGetPreSignedUrlArgs {
	return &VideoSvrGetPreSignedUrlArgs{}
}

func (p *VideoSvrGetPreSignedUrlArgs) InitDefault() {
}

var VideoSvrGetPreSignedUrlArgs_Req_DEFAULT *GetPreSignedUrlReq

func (p *VideoSvrGetPreSignedUrlArgs) GetReq() (v *GetPreSignedUrlReq) {
	if !p.IsSetReq() {
		return VideoSvrGetPreSignedUrlArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *VideoSvrGetPreSignedUrlArgs) SetReq(val *GetPreSignedUrlReq) {
	p.Req = val
}

func (p *VideoSvrGetPreSignedUrlArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *VideoSvrGetPreSignedUrlArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoSvrGetPreSignedUrlArgs(%+v)", *p)
}

var fieldIDToName_VideoSvrGetPreSignedUrlArgs = map[int16]string{
	1: "req",
}

type VideoSvrGetPreSignedUrlResult struct {
	Success *GetPreSignedUrlResp `thrift:"success,0,optional" frugal:"0,optional,GetPreSignedUrlResp" json:"success,omitempty"`
}

func NewVideoSvrGetPreSignedUrlResult() *VideoSvrGetPreSignedUrlResult {
	return &VideoSvrGetPreSignedUrlResult{}
}

func (p *VideoSvrGetPreSignedUrlResult) InitDefault() {
}

var VideoSvrGetPreSignedUrlResult_Success_DEFAULT *GetPreSignedUrlResp

func (p *VideoSvrGetPreSignedUrlResult) GetSuccess() (v *GetPreSignedUrlResp) {
	if !p.IsSetSuccess() {
		return VideoSvrGetPreSignedUrlResult_Success_DEFAULT
	}
	return p.Success
}
func (p *VideoSvrGetPreSignedUrlResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetPreSignedUrlResp)
}

func (p *VideoSvrGetPreSignedUrlResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *VideoSvrGetPreSignedUrlResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("VideoSvrGetPreSignedUrlResult(%+v)", *p)
}

var fieldIDToName_VideoSvrGetPreSignedUrlResult = map[int16]string{
	0: "success",
}
