// Code generated by Kitex v0.15.4. DO NOT EDIT.

package usersvr

import (
	usersvr "LiveDanmu/apps/rpc/livesvr/kitex_gen/usersvr"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"UserLogin": kitex.NewMethodInfo(
		userLoginHandler,
		newUserSvrUserLoginArgs,
		newUserSvrUserLoginResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"RefreshToken": kitex.NewMethodInfo(
		refreshTokenHandler,
		newUserSvrRefreshTokenArgs,
		newUserSvrRefreshTokenResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUserInfo": kitex.NewMethodInfo(
		getUserInfoHandler,
		newUserSvrGetUserInfoArgs,
		newUserSvrGetUserInfoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"SetAdminRole": kitex.NewMethodInfo(
		setAdminRoleHandler,
		newUserSvrSetAdminRoleArgs,
		newUserSvrSetAdminRoleResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetAdminer": kitex.NewMethodInfo(
		getAdminerHandler,
		newUserSvrGetAdminerArgs,
		newUserSvrGetAdminerResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetUsers": kitex.NewMethodInfo(
		getUsersHandler,
		newUserSvrGetUsersArgs,
		newUserSvrGetUsersResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"Logout": kitex.NewMethodInfo(
		logoutHandler,
		newUserSvrLogoutArgs,
		newUserSvrLogoutResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	userSvrServiceInfo                = NewServiceInfo()
	userSvrServiceInfoForClient       = NewServiceInfoForClient()
	userSvrServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return userSvrServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return userSvrServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return userSvrServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "UserSvr"
	handlerType := (*usersvr.UserSvr)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "usersvr",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.4",
		Extra:           extra,
	}
	return svcInfo
}

func userLoginHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*usersvr.UserSvrUserLoginArgs)
	realResult := result.(*usersvr.UserSvrUserLoginResult)
	success, err := handler.(usersvr.UserSvr).UserLogin(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserSvrUserLoginArgs() interface{} {
	return usersvr.NewUserSvrUserLoginArgs()
}

func newUserSvrUserLoginResult() interface{} {
	return usersvr.NewUserSvrUserLoginResult()
}

func refreshTokenHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*usersvr.UserSvrRefreshTokenArgs)
	realResult := result.(*usersvr.UserSvrRefreshTokenResult)
	success, err := handler.(usersvr.UserSvr).RefreshToken(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserSvrRefreshTokenArgs() interface{} {
	return usersvr.NewUserSvrRefreshTokenArgs()
}

func newUserSvrRefreshTokenResult() interface{} {
	return usersvr.NewUserSvrRefreshTokenResult()
}

func getUserInfoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*usersvr.UserSvrGetUserInfoArgs)
	realResult := result.(*usersvr.UserSvrGetUserInfoResult)
	success, err := handler.(usersvr.UserSvr).GetUserInfo(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserSvrGetUserInfoArgs() interface{} {
	return usersvr.NewUserSvrGetUserInfoArgs()
}

func newUserSvrGetUserInfoResult() interface{} {
	return usersvr.NewUserSvrGetUserInfoResult()
}

func setAdminRoleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*usersvr.UserSvrSetAdminRoleArgs)
	realResult := result.(*usersvr.UserSvrSetAdminRoleResult)
	success, err := handler.(usersvr.UserSvr).SetAdminRole(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserSvrSetAdminRoleArgs() interface{} {
	return usersvr.NewUserSvrSetAdminRoleArgs()
}

func newUserSvrSetAdminRoleResult() interface{} {
	return usersvr.NewUserSvrSetAdminRoleResult()
}

func getAdminerHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*usersvr.UserSvrGetAdminerArgs)
	realResult := result.(*usersvr.UserSvrGetAdminerResult)
	success, err := handler.(usersvr.UserSvr).GetAdminer(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserSvrGetAdminerArgs() interface{} {
	return usersvr.NewUserSvrGetAdminerArgs()
}

func newUserSvrGetAdminerResult() interface{} {
	return usersvr.NewUserSvrGetAdminerResult()
}

func getUsersHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*usersvr.UserSvrGetUsersArgs)
	realResult := result.(*usersvr.UserSvrGetUsersResult)
	success, err := handler.(usersvr.UserSvr).GetUsers(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserSvrGetUsersArgs() interface{} {
	return usersvr.NewUserSvrGetUsersArgs()
}

func newUserSvrGetUsersResult() interface{} {
	return usersvr.NewUserSvrGetUsersResult()
}

func logoutHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*usersvr.UserSvrLogoutArgs)
	realResult := result.(*usersvr.UserSvrLogoutResult)
	success, err := handler.(usersvr.UserSvr).Logout(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserSvrLogoutArgs() interface{} {
	return usersvr.NewUserSvrLogoutArgs()
}

func newUserSvrLogoutResult() interface{} {
	return usersvr.NewUserSvrLogoutResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) UserLogin(ctx context.Context, req *usersvr.LoginReq) (r *usersvr.LoginResp, err error) {
	var _args usersvr.UserSvrUserLoginArgs
	_args.Req = req
	var _result usersvr.UserSvrUserLoginResult
	if err = p.c.Call(ctx, "UserLogin", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) RefreshToken(ctx context.Context, req *usersvr.RefreshReq) (r *usersvr.RefreshResp, err error) {
	var _args usersvr.UserSvrRefreshTokenArgs
	_args.Req = req
	var _result usersvr.UserSvrRefreshTokenResult
	if err = p.c.Call(ctx, "RefreshToken", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUserInfo(ctx context.Context, req *usersvr.GetUserInfoReq) (r *usersvr.GetUserInfoResp, err error) {
	var _args usersvr.UserSvrGetUserInfoArgs
	_args.Req = req
	var _result usersvr.UserSvrGetUserInfoResult
	if err = p.c.Call(ctx, "GetUserInfo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) SetAdminRole(ctx context.Context, req *usersvr.SetAdminRoleReq) (r *usersvr.SetAdminRoleResp, err error) {
	var _args usersvr.UserSvrSetAdminRoleArgs
	_args.Req = req
	var _result usersvr.UserSvrSetAdminRoleResult
	if err = p.c.Call(ctx, "SetAdminRole", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetAdminer(ctx context.Context, req *usersvr.GetAdminerReq) (r *usersvr.GetAdminerResp, err error) {
	var _args usersvr.UserSvrGetAdminerArgs
	_args.Req = req
	var _result usersvr.UserSvrGetAdminerResult
	if err = p.c.Call(ctx, "GetAdminer", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetUsers(ctx context.Context, req *usersvr.GetUsersReq) (r *usersvr.GetUsersResp, err error) {
	var _args usersvr.UserSvrGetUsersArgs
	_args.Req = req
	var _result usersvr.UserSvrGetUsersResult
	if err = p.c.Call(ctx, "GetUsers", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Logout(ctx context.Context, req *usersvr.LogoutReq) (r *usersvr.LogoutResp, err error) {
	var _args usersvr.UserSvrLogoutArgs
	_args.Req = req
	var _result usersvr.UserSvrLogoutResult
	if err = p.c.Call(ctx, "Logout", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
