// Code generated by Kitex v0.16.0. DO NOT EDIT.

package danmusvr

import (
	danmusvr "LiveDanmu/apps/rpc/danmusvr/kitex_gen/danmusvr"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	PubDanmu(ctx context.Context, req *danmusvr.PubReq, callOptions ...callopt.Option) (r *danmusvr.PubResp, err error)
	PubLiveDanmu(ctx context.Context, req *danmusvr.PubLiveReq, callOptions ...callopt.Option) (r *danmusvr.PubLiveResp, err error)
	GetDanmu(ctx context.Context, req *danmusvr.GetReq, callOptions ...callopt.Option) (r *danmusvr.GetResp, err error)
	GetTop(ctx context.Context, req *danmusvr.GetTopReq, callOptions ...callopt.Option) (r *danmusvr.GetTopResp, err error)
	DelLiveDanmu(ctx context.Context, req *danmusvr.DelLiveReq, callOptions ...callopt.Option) (r *danmusvr.DelLiveResp, err error)
	DelDanmu(ctx context.Context, req *danmusvr.DelReq, callOptions ...callopt.Option) (r *danmusvr.DelResp, err error)
}

// NewClient creates a client for the service_tag.yaml defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kDanmuSvrClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service_tag.yaml defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kDanmuSvrClient struct {
	*kClient
}

func (p *kDanmuSvrClient) PubDanmu(ctx context.Context, req *danmusvr.PubReq, callOptions ...callopt.Option) (r *danmusvr.PubResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PubDanmu(ctx, req)
}

func (p *kDanmuSvrClient) PubLiveDanmu(ctx context.Context, req *danmusvr.PubLiveReq, callOptions ...callopt.Option) (r *danmusvr.PubLiveResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PubLiveDanmu(ctx, req)
}

func (p *kDanmuSvrClient) GetDanmu(ctx context.Context, req *danmusvr.GetReq, callOptions ...callopt.Option) (r *danmusvr.GetResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetDanmu(ctx, req)
}

func (p *kDanmuSvrClient) GetTop(ctx context.Context, req *danmusvr.GetTopReq, callOptions ...callopt.Option) (r *danmusvr.GetTopResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetTop(ctx, req)
}

func (p *kDanmuSvrClient) DelLiveDanmu(ctx context.Context, req *danmusvr.DelLiveReq, callOptions ...callopt.Option) (r *danmusvr.DelLiveResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DelLiveDanmu(ctx, req)
}

func (p *kDanmuSvrClient) DelDanmu(ctx context.Context, req *danmusvr.DelReq, callOptions ...callopt.Option) (r *danmusvr.DelResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DelDanmu(ctx, req)
}
