// Code generated by Kitex v0.15.4. DO NOT EDIT.

package danmusvr

import (
	danmusvr "LiveDanmu/apps/rpc/danmusvr/kitex_gen/danmusvr"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"PubVideoDanmu": kitex.NewMethodInfo(
		pubVideoDanmuHandler,
		newDanmuSvrPubVideoDanmuArgs,
		newDanmuSvrPubVideoDanmuResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"PubLiveDanmu": kitex.NewMethodInfo(
		pubLiveDanmuHandler,
		newDanmuSvrPubLiveDanmuArgs,
		newDanmuSvrPubLiveDanmuResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetDanmu": kitex.NewMethodInfo(
		getDanmuHandler,
		newDanmuSvrGetDanmuArgs,
		newDanmuSvrGetDanmuResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetTop": kitex.NewMethodInfo(
		getTopHandler,
		newDanmuSvrGetTopArgs,
		newDanmuSvrGetTopResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DelLiveDanmu": kitex.NewMethodInfo(
		delLiveDanmuHandler,
		newDanmuSvrDelLiveDanmuArgs,
		newDanmuSvrDelLiveDanmuResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DelDanmu": kitex.NewMethodInfo(
		delDanmuHandler,
		newDanmuSvrDelDanmuArgs,
		newDanmuSvrDelDanmuResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	danmuSvrServiceInfo                = NewServiceInfo()
	danmuSvrServiceInfoForClient       = NewServiceInfoForClient()
	danmuSvrServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return danmuSvrServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return danmuSvrServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return danmuSvrServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "DanmuSvr"
	handlerType := (*danmusvr.DanmuSvr)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "danmusvr",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.4",
		Extra:           extra,
	}
	return svcInfo
}

func pubVideoDanmuHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*danmusvr.DanmuSvrPubVideoDanmuArgs)
	realResult := result.(*danmusvr.DanmuSvrPubVideoDanmuResult)
	success, err := handler.(danmusvr.DanmuSvr).PubVideoDanmu(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDanmuSvrPubVideoDanmuArgs() interface{} {
	return danmusvr.NewDanmuSvrPubVideoDanmuArgs()
}

func newDanmuSvrPubVideoDanmuResult() interface{} {
	return danmusvr.NewDanmuSvrPubVideoDanmuResult()
}

func pubLiveDanmuHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*danmusvr.DanmuSvrPubLiveDanmuArgs)
	realResult := result.(*danmusvr.DanmuSvrPubLiveDanmuResult)
	success, err := handler.(danmusvr.DanmuSvr).PubLiveDanmu(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDanmuSvrPubLiveDanmuArgs() interface{} {
	return danmusvr.NewDanmuSvrPubLiveDanmuArgs()
}

func newDanmuSvrPubLiveDanmuResult() interface{} {
	return danmusvr.NewDanmuSvrPubLiveDanmuResult()
}

func getDanmuHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*danmusvr.DanmuSvrGetDanmuArgs)
	realResult := result.(*danmusvr.DanmuSvrGetDanmuResult)
	success, err := handler.(danmusvr.DanmuSvr).GetDanmu(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDanmuSvrGetDanmuArgs() interface{} {
	return danmusvr.NewDanmuSvrGetDanmuArgs()
}

func newDanmuSvrGetDanmuResult() interface{} {
	return danmusvr.NewDanmuSvrGetDanmuResult()
}

func getTopHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*danmusvr.DanmuSvrGetTopArgs)
	realResult := result.(*danmusvr.DanmuSvrGetTopResult)
	success, err := handler.(danmusvr.DanmuSvr).GetTop(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDanmuSvrGetTopArgs() interface{} {
	return danmusvr.NewDanmuSvrGetTopArgs()
}

func newDanmuSvrGetTopResult() interface{} {
	return danmusvr.NewDanmuSvrGetTopResult()
}

func delLiveDanmuHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*danmusvr.DanmuSvrDelLiveDanmuArgs)
	realResult := result.(*danmusvr.DanmuSvrDelLiveDanmuResult)
	success, err := handler.(danmusvr.DanmuSvr).DelLiveDanmu(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDanmuSvrDelLiveDanmuArgs() interface{} {
	return danmusvr.NewDanmuSvrDelLiveDanmuArgs()
}

func newDanmuSvrDelLiveDanmuResult() interface{} {
	return danmusvr.NewDanmuSvrDelLiveDanmuResult()
}

func delDanmuHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*danmusvr.DanmuSvrDelDanmuArgs)
	realResult := result.(*danmusvr.DanmuSvrDelDanmuResult)
	success, err := handler.(danmusvr.DanmuSvr).DelDanmu(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newDanmuSvrDelDanmuArgs() interface{} {
	return danmusvr.NewDanmuSvrDelDanmuArgs()
}

func newDanmuSvrDelDanmuResult() interface{} {
	return danmusvr.NewDanmuSvrDelDanmuResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) PubVideoDanmu(ctx context.Context, req *danmusvr.PubVideoReq) (r *danmusvr.PubVideoResp, err error) {
	var _args danmusvr.DanmuSvrPubVideoDanmuArgs
	_args.Req = req
	var _result danmusvr.DanmuSvrPubVideoDanmuResult
	if err = p.c.Call(ctx, "PubVideoDanmu", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) PubLiveDanmu(ctx context.Context, req *danmusvr.PubLiveReq) (r *danmusvr.PubLiveResp, err error) {
	var _args danmusvr.DanmuSvrPubLiveDanmuArgs
	_args.Req = req
	var _result danmusvr.DanmuSvrPubLiveDanmuResult
	if err = p.c.Call(ctx, "PubLiveDanmu", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetDanmu(ctx context.Context, req *danmusvr.GetFullReq) (r *danmusvr.GetFullResp, err error) {
	var _args danmusvr.DanmuSvrGetDanmuArgs
	_args.Req = req
	var _result danmusvr.DanmuSvrGetDanmuResult
	if err = p.c.Call(ctx, "GetDanmu", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetTop(ctx context.Context, req *danmusvr.GetTopReq) (r *danmusvr.GetTopResp, err error) {
	var _args danmusvr.DanmuSvrGetTopArgs
	_args.Req = req
	var _result danmusvr.DanmuSvrGetTopResult
	if err = p.c.Call(ctx, "GetTop", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DelLiveDanmu(ctx context.Context, req *danmusvr.DelLiveReq) (r *danmusvr.DelLiveResp, err error) {
	var _args danmusvr.DanmuSvrDelLiveDanmuArgs
	_args.Req = req
	var _result danmusvr.DanmuSvrDelLiveDanmuResult
	if err = p.c.Call(ctx, "DelLiveDanmu", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DelDanmu(ctx context.Context, req *danmusvr.DelReq) (r *danmusvr.DelResp, err error) {
	var _args danmusvr.DanmuSvrDelDanmuArgs
	_args.Req = req
	var _result danmusvr.DanmuSvrDelDanmuResult
	if err = p.c.Call(ctx, "DelDanmu", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
