// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package usersvr

import (
	"context"
	"fmt"
)

type RvUserInfo struct {
	Uid       int64  `thrift:"uid,1,required" frugal:"1,required,i64" json:"uid"`
	UserName  string `thrift:"user_name,2,required" frugal:"2,required,string" json:"user_name"`
	AvatarUrl string `thrift:"avatar_url,3,required" frugal:"3,required,string" json:"avatar_url"`
	Bio       string `thrift:"bio,4,required" frugal:"4,required,string" json:"bio"`
}

func NewRvUserInfo() *RvUserInfo {
	return &RvUserInfo{}
}

func (p *RvUserInfo) InitDefault() {
}

func (p *RvUserInfo) GetUid() (v int64) {
	return p.Uid
}

func (p *RvUserInfo) GetUserName() (v string) {
	return p.UserName
}

func (p *RvUserInfo) GetAvatarUrl() (v string) {
	return p.AvatarUrl
}

func (p *RvUserInfo) GetBio() (v string) {
	return p.Bio
}
func (p *RvUserInfo) SetUid(val int64) {
	p.Uid = val
}
func (p *RvUserInfo) SetUserName(val string) {
	p.UserName = val
}
func (p *RvUserInfo) SetAvatarUrl(val string) {
	p.AvatarUrl = val
}
func (p *RvUserInfo) SetBio(val string) {
	p.Bio = val
}

func (p *RvUserInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RvUserInfo(%+v)", *p)
}

var fieldIDToName_RvUserInfo = map[int16]string{
	1: "uid",
	2: "user_name",
	3: "avatar_url",
	4: "bio",
}

type LoginReq struct {
	UserInfo *RvUserInfo `thrift:"user_info,1,required" frugal:"1,required,RvUserInfo" json:"user_info"`
}

func NewLoginReq() *LoginReq {
	return &LoginReq{}
}

func (p *LoginReq) InitDefault() {
}

var LoginReq_UserInfo_DEFAULT *RvUserInfo

func (p *LoginReq) GetUserInfo() (v *RvUserInfo) {
	if !p.IsSetUserInfo() {
		return LoginReq_UserInfo_DEFAULT
	}
	return p.UserInfo
}
func (p *LoginReq) SetUserInfo(val *RvUserInfo) {
	p.UserInfo = val
}

func (p *LoginReq) IsSetUserInfo() bool {
	return p.UserInfo != nil
}

func (p *LoginReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginReq(%+v)", *p)
}

var fieldIDToName_LoginReq = map[int16]string{
	1: "user_info",
}

type LoginResp struct {
	Status int64   `thrift:"status,1,required" frugal:"1,required,i64" json:"status"`
	Info   string  `thrift:"info,2,required" frugal:"2,required,string" json:"info"`
	Data   *string `thrift:"data,3,optional" frugal:"3,optional,string" json:"data,omitempty"`
}

func NewLoginResp() *LoginResp {
	return &LoginResp{}
}

func (p *LoginResp) InitDefault() {
}

func (p *LoginResp) GetStatus() (v int64) {
	return p.Status
}

func (p *LoginResp) GetInfo() (v string) {
	return p.Info
}

var LoginResp_Data_DEFAULT string

func (p *LoginResp) GetData() (v string) {
	if !p.IsSetData() {
		return LoginResp_Data_DEFAULT
	}
	return *p.Data
}
func (p *LoginResp) SetStatus(val int64) {
	p.Status = val
}
func (p *LoginResp) SetInfo(val string) {
	p.Info = val
}
func (p *LoginResp) SetData(val *string) {
	p.Data = val
}

func (p *LoginResp) IsSetData() bool {
	return p.Data != nil
}

func (p *LoginResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginResp(%+v)", *p)
}

var fieldIDToName_LoginResp = map[int16]string{
	1: "status",
	2: "info",
	3: "data",
}

type RefreshReq struct {
	RefreshToken string `thrift:"refreshToken,1,required" frugal:"1,required,string" json:"refreshToken"`
}

func NewRefreshReq() *RefreshReq {
	return &RefreshReq{}
}

func (p *RefreshReq) InitDefault() {
}

func (p *RefreshReq) GetRefreshToken() (v string) {
	return p.RefreshToken
}
func (p *RefreshReq) SetRefreshToken(val string) {
	p.RefreshToken = val
}

func (p *RefreshReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefreshReq(%+v)", *p)
}

var fieldIDToName_RefreshReq = map[int16]string{
	1: "refreshToken",
}

type RefreshResp struct {
	Status int64   `thrift:"status,1,required" frugal:"1,required,i64" json:"status"`
	Info   string  `thrift:"info,2,required" frugal:"2,required,string" json:"info"`
	Data   *string `thrift:"data,3,optional" frugal:"3,optional,string" json:"data,omitempty"`
}

func NewRefreshResp() *RefreshResp {
	return &RefreshResp{}
}

func (p *RefreshResp) InitDefault() {
}

func (p *RefreshResp) GetStatus() (v int64) {
	return p.Status
}

func (p *RefreshResp) GetInfo() (v string) {
	return p.Info
}

var RefreshResp_Data_DEFAULT string

func (p *RefreshResp) GetData() (v string) {
	if !p.IsSetData() {
		return RefreshResp_Data_DEFAULT
	}
	return *p.Data
}
func (p *RefreshResp) SetStatus(val int64) {
	p.Status = val
}
func (p *RefreshResp) SetInfo(val string) {
	p.Info = val
}
func (p *RefreshResp) SetData(val *string) {
	p.Data = val
}

func (p *RefreshResp) IsSetData() bool {
	return p.Data != nil
}

func (p *RefreshResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefreshResp(%+v)", *p)
}

var fieldIDToName_RefreshResp = map[int16]string{
	1: "status",
	2: "info",
	3: "data",
}

type GetUserInfoReq struct {
	Uid int64 `thrift:"uid,1,required" frugal:"1,required,i64" json:"uid"`
}

func NewGetUserInfoReq() *GetUserInfoReq {
	return &GetUserInfoReq{}
}

func (p *GetUserInfoReq) InitDefault() {
}

func (p *GetUserInfoReq) GetUid() (v int64) {
	return p.Uid
}
func (p *GetUserInfoReq) SetUid(val int64) {
	p.Uid = val
}

func (p *GetUserInfoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserInfoReq(%+v)", *p)
}

var fieldIDToName_GetUserInfoReq = map[int16]string{
	1: "uid",
}

type GetUserInfoResp struct {
	Status int64       `thrift:"status,1,required" frugal:"1,required,i64" json:"status"`
	Info   string      `thrift:"info,2,required" frugal:"2,required,string" json:"info"`
	Data   *RvUserInfo `thrift:"data,3,optional" frugal:"3,optional,RvUserInfo" json:"data,omitempty"`
}

func NewGetUserInfoResp() *GetUserInfoResp {
	return &GetUserInfoResp{}
}

func (p *GetUserInfoResp) InitDefault() {
}

func (p *GetUserInfoResp) GetStatus() (v int64) {
	return p.Status
}

func (p *GetUserInfoResp) GetInfo() (v string) {
	return p.Info
}

var GetUserInfoResp_Data_DEFAULT *RvUserInfo

func (p *GetUserInfoResp) GetData() (v *RvUserInfo) {
	if !p.IsSetData() {
		return GetUserInfoResp_Data_DEFAULT
	}
	return p.Data
}
func (p *GetUserInfoResp) SetStatus(val int64) {
	p.Status = val
}
func (p *GetUserInfoResp) SetInfo(val string) {
	p.Info = val
}
func (p *GetUserInfoResp) SetData(val *RvUserInfo) {
	p.Data = val
}

func (p *GetUserInfoResp) IsSetData() bool {
	return p.Data != nil
}

func (p *GetUserInfoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserInfoResp(%+v)", *p)
}

var fieldIDToName_GetUserInfoResp = map[int16]string{
	1: "status",
	2: "info",
	3: "data",
}

type UserSvr interface {
	UserLogin(ctx context.Context, req *LoginReq) (r *LoginResp, err error)

	RefreshToken(ctx context.Context, req *RefreshReq) (r *RefreshResp, err error)

	GetUserInfo(ctx context.Context, req *GetUserInfoReq) (r *GetUserInfoResp, err error)
}

type UserSvrUserLoginArgs struct {
	Req *LoginReq `thrift:"req,1" frugal:"1,default,LoginReq" json:"req"`
}

func NewUserSvrUserLoginArgs() *UserSvrUserLoginArgs {
	return &UserSvrUserLoginArgs{}
}

func (p *UserSvrUserLoginArgs) InitDefault() {
}

var UserSvrUserLoginArgs_Req_DEFAULT *LoginReq

func (p *UserSvrUserLoginArgs) GetReq() (v *LoginReq) {
	if !p.IsSetReq() {
		return UserSvrUserLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserSvrUserLoginArgs) SetReq(val *LoginReq) {
	p.Req = val
}

func (p *UserSvrUserLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserSvrUserLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserSvrUserLoginArgs(%+v)", *p)
}

var fieldIDToName_UserSvrUserLoginArgs = map[int16]string{
	1: "req",
}

type UserSvrUserLoginResult struct {
	Success *LoginResp `thrift:"success,0,optional" frugal:"0,optional,LoginResp" json:"success,omitempty"`
}

func NewUserSvrUserLoginResult() *UserSvrUserLoginResult {
	return &UserSvrUserLoginResult{}
}

func (p *UserSvrUserLoginResult) InitDefault() {
}

var UserSvrUserLoginResult_Success_DEFAULT *LoginResp

func (p *UserSvrUserLoginResult) GetSuccess() (v *LoginResp) {
	if !p.IsSetSuccess() {
		return UserSvrUserLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserSvrUserLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*LoginResp)
}

func (p *UserSvrUserLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserSvrUserLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserSvrUserLoginResult(%+v)", *p)
}

var fieldIDToName_UserSvrUserLoginResult = map[int16]string{
	0: "success",
}

type UserSvrRefreshTokenArgs struct {
	Req *RefreshReq `thrift:"req,1" frugal:"1,default,RefreshReq" json:"req"`
}

func NewUserSvrRefreshTokenArgs() *UserSvrRefreshTokenArgs {
	return &UserSvrRefreshTokenArgs{}
}

func (p *UserSvrRefreshTokenArgs) InitDefault() {
}

var UserSvrRefreshTokenArgs_Req_DEFAULT *RefreshReq

func (p *UserSvrRefreshTokenArgs) GetReq() (v *RefreshReq) {
	if !p.IsSetReq() {
		return UserSvrRefreshTokenArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserSvrRefreshTokenArgs) SetReq(val *RefreshReq) {
	p.Req = val
}

func (p *UserSvrRefreshTokenArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserSvrRefreshTokenArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserSvrRefreshTokenArgs(%+v)", *p)
}

var fieldIDToName_UserSvrRefreshTokenArgs = map[int16]string{
	1: "req",
}

type UserSvrRefreshTokenResult struct {
	Success *RefreshResp `thrift:"success,0,optional" frugal:"0,optional,RefreshResp" json:"success,omitempty"`
}

func NewUserSvrRefreshTokenResult() *UserSvrRefreshTokenResult {
	return &UserSvrRefreshTokenResult{}
}

func (p *UserSvrRefreshTokenResult) InitDefault() {
}

var UserSvrRefreshTokenResult_Success_DEFAULT *RefreshResp

func (p *UserSvrRefreshTokenResult) GetSuccess() (v *RefreshResp) {
	if !p.IsSetSuccess() {
		return UserSvrRefreshTokenResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserSvrRefreshTokenResult) SetSuccess(x interface{}) {
	p.Success = x.(*RefreshResp)
}

func (p *UserSvrRefreshTokenResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserSvrRefreshTokenResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserSvrRefreshTokenResult(%+v)", *p)
}

var fieldIDToName_UserSvrRefreshTokenResult = map[int16]string{
	0: "success",
}

type UserSvrGetUserInfoArgs struct {
	Req *GetUserInfoReq `thrift:"req,1" frugal:"1,default,GetUserInfoReq" json:"req"`
}

func NewUserSvrGetUserInfoArgs() *UserSvrGetUserInfoArgs {
	return &UserSvrGetUserInfoArgs{}
}

func (p *UserSvrGetUserInfoArgs) InitDefault() {
}

var UserSvrGetUserInfoArgs_Req_DEFAULT *GetUserInfoReq

func (p *UserSvrGetUserInfoArgs) GetReq() (v *GetUserInfoReq) {
	if !p.IsSetReq() {
		return UserSvrGetUserInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserSvrGetUserInfoArgs) SetReq(val *GetUserInfoReq) {
	p.Req = val
}

func (p *UserSvrGetUserInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserSvrGetUserInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserSvrGetUserInfoArgs(%+v)", *p)
}

var fieldIDToName_UserSvrGetUserInfoArgs = map[int16]string{
	1: "req",
}

type UserSvrGetUserInfoResult struct {
	Success *GetUserInfoResp `thrift:"success,0,optional" frugal:"0,optional,GetUserInfoResp" json:"success,omitempty"`
}

func NewUserSvrGetUserInfoResult() *UserSvrGetUserInfoResult {
	return &UserSvrGetUserInfoResult{}
}

func (p *UserSvrGetUserInfoResult) InitDefault() {
}

var UserSvrGetUserInfoResult_Success_DEFAULT *GetUserInfoResp

func (p *UserSvrGetUserInfoResult) GetSuccess() (v *GetUserInfoResp) {
	if !p.IsSetSuccess() {
		return UserSvrGetUserInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserSvrGetUserInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUserInfoResp)
}

func (p *UserSvrGetUserInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserSvrGetUserInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserSvrGetUserInfoResult(%+v)", *p)
}

var fieldIDToName_UserSvrGetUserInfoResult = map[int16]string{
	0: "success",
}
