// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package usersvr

import (
	"context"
	"fmt"
)

type RvUserInfo struct {
	Uid       int64  `thrift:"uid,1,required" frugal:"1,required,i64" json:"uid"`
	UserName  string `thrift:"user_name,2,required" frugal:"2,required,string" json:"user_name"`
	AvatarUrl string `thrift:"avatar_url,3,required" frugal:"3,required,string" json:"avatar_url"`
	Bio       string `thrift:"bio,4,required" frugal:"4,required,string" json:"bio"`
	Role      string `thrift:"role,5,required" frugal:"5,required,string" json:"role"`
}

func NewRvUserInfo() *RvUserInfo {
	return &RvUserInfo{}
}

func (p *RvUserInfo) InitDefault() {
}

func (p *RvUserInfo) GetUid() (v int64) {
	return p.Uid
}

func (p *RvUserInfo) GetUserName() (v string) {
	return p.UserName
}

func (p *RvUserInfo) GetAvatarUrl() (v string) {
	return p.AvatarUrl
}

func (p *RvUserInfo) GetBio() (v string) {
	return p.Bio
}

func (p *RvUserInfo) GetRole() (v string) {
	return p.Role
}
func (p *RvUserInfo) SetUid(val int64) {
	p.Uid = val
}
func (p *RvUserInfo) SetUserName(val string) {
	p.UserName = val
}
func (p *RvUserInfo) SetAvatarUrl(val string) {
	p.AvatarUrl = val
}
func (p *RvUserInfo) SetBio(val string) {
	p.Bio = val
}
func (p *RvUserInfo) SetRole(val string) {
	p.Role = val
}

func (p *RvUserInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RvUserInfo(%+v)", *p)
}

var fieldIDToName_RvUserInfo = map[int16]string{
	1: "uid",
	2: "user_name",
	3: "avatar_url",
	4: "bio",
	5: "role",
}

type LoginData struct {
	AccessToken  string `thrift:"accessToken,1,required" frugal:"1,required,string" json:"accessToken"`
	RefreshToken string `thrift:"refreshToken,2,required" frugal:"2,required,string" json:"refreshToken"`
}

func NewLoginData() *LoginData {
	return &LoginData{}
}

func (p *LoginData) InitDefault() {
}

func (p *LoginData) GetAccessToken() (v string) {
	return p.AccessToken
}

func (p *LoginData) GetRefreshToken() (v string) {
	return p.RefreshToken
}
func (p *LoginData) SetAccessToken(val string) {
	p.AccessToken = val
}
func (p *LoginData) SetRefreshToken(val string) {
	p.RefreshToken = val
}

func (p *LoginData) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginData(%+v)", *p)
}

var fieldIDToName_LoginData = map[int16]string{
	1: "accessToken",
	2: "refreshToken",
}

type LoginReq struct {
	UserInfo *RvUserInfo `thrift:"user_info,1,required" frugal:"1,required,RvUserInfo" json:"user_info"`
}

func NewLoginReq() *LoginReq {
	return &LoginReq{}
}

func (p *LoginReq) InitDefault() {
}

var LoginReq_UserInfo_DEFAULT *RvUserInfo

func (p *LoginReq) GetUserInfo() (v *RvUserInfo) {
	if !p.IsSetUserInfo() {
		return LoginReq_UserInfo_DEFAULT
	}
	return p.UserInfo
}
func (p *LoginReq) SetUserInfo(val *RvUserInfo) {
	p.UserInfo = val
}

func (p *LoginReq) IsSetUserInfo() bool {
	return p.UserInfo != nil
}

func (p *LoginReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginReq(%+v)", *p)
}

var fieldIDToName_LoginReq = map[int16]string{
	1: "user_info",
}

type LoginResp struct {
	Status int64      `thrift:"status,1,required" frugal:"1,required,i64" json:"status"`
	Info   string     `thrift:"info,2,required" frugal:"2,required,string" json:"info"`
	Data   *LoginData `thrift:"data,3,optional" frugal:"3,optional,LoginData" json:"data,omitempty"`
}

func NewLoginResp() *LoginResp {
	return &LoginResp{}
}

func (p *LoginResp) InitDefault() {
}

func (p *LoginResp) GetStatus() (v int64) {
	return p.Status
}

func (p *LoginResp) GetInfo() (v string) {
	return p.Info
}

var LoginResp_Data_DEFAULT *LoginData

func (p *LoginResp) GetData() (v *LoginData) {
	if !p.IsSetData() {
		return LoginResp_Data_DEFAULT
	}
	return p.Data
}
func (p *LoginResp) SetStatus(val int64) {
	p.Status = val
}
func (p *LoginResp) SetInfo(val string) {
	p.Info = val
}
func (p *LoginResp) SetData(val *LoginData) {
	p.Data = val
}

func (p *LoginResp) IsSetData() bool {
	return p.Data != nil
}

func (p *LoginResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginResp(%+v)", *p)
}

var fieldIDToName_LoginResp = map[int16]string{
	1: "status",
	2: "info",
	3: "data",
}

type RefreshReq struct {
	RefreshToken string `thrift:"refreshToken,1,required" frugal:"1,required,string" json:"refreshToken"`
}

func NewRefreshReq() *RefreshReq {
	return &RefreshReq{}
}

func (p *RefreshReq) InitDefault() {
}

func (p *RefreshReq) GetRefreshToken() (v string) {
	return p.RefreshToken
}
func (p *RefreshReq) SetRefreshToken(val string) {
	p.RefreshToken = val
}

func (p *RefreshReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefreshReq(%+v)", *p)
}

var fieldIDToName_RefreshReq = map[int16]string{
	1: "refreshToken",
}

type RefreshResp struct {
	Status int64   `thrift:"status,1,required" frugal:"1,required,i64" json:"status"`
	Info   string  `thrift:"info,2,required" frugal:"2,required,string" json:"info"`
	Data   *string `thrift:"data,3,optional" frugal:"3,optional,string" json:"data,omitempty"`
}

func NewRefreshResp() *RefreshResp {
	return &RefreshResp{}
}

func (p *RefreshResp) InitDefault() {
}

func (p *RefreshResp) GetStatus() (v int64) {
	return p.Status
}

func (p *RefreshResp) GetInfo() (v string) {
	return p.Info
}

var RefreshResp_Data_DEFAULT string

func (p *RefreshResp) GetData() (v string) {
	if !p.IsSetData() {
		return RefreshResp_Data_DEFAULT
	}
	return *p.Data
}
func (p *RefreshResp) SetStatus(val int64) {
	p.Status = val
}
func (p *RefreshResp) SetInfo(val string) {
	p.Info = val
}
func (p *RefreshResp) SetData(val *string) {
	p.Data = val
}

func (p *RefreshResp) IsSetData() bool {
	return p.Data != nil
}

func (p *RefreshResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RefreshResp(%+v)", *p)
}

var fieldIDToName_RefreshResp = map[int16]string{
	1: "status",
	2: "info",
	3: "data",
}

type GetUserInfoReq struct {
	Uid int64 `thrift:"uid,1,required" frugal:"1,required,i64" json:"uid"`
}

func NewGetUserInfoReq() *GetUserInfoReq {
	return &GetUserInfoReq{}
}

func (p *GetUserInfoReq) InitDefault() {
}

func (p *GetUserInfoReq) GetUid() (v int64) {
	return p.Uid
}
func (p *GetUserInfoReq) SetUid(val int64) {
	p.Uid = val
}

func (p *GetUserInfoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserInfoReq(%+v)", *p)
}

var fieldIDToName_GetUserInfoReq = map[int16]string{
	1: "uid",
}

type GetUserInfoResp struct {
	Status int64       `thrift:"status,1,required" frugal:"1,required,i64" json:"status"`
	Info   string      `thrift:"info,2,required" frugal:"2,required,string" json:"info"`
	Data   *RvUserInfo `thrift:"data,3,optional" frugal:"3,optional,RvUserInfo" json:"data,omitempty"`
}

func NewGetUserInfoResp() *GetUserInfoResp {
	return &GetUserInfoResp{}
}

func (p *GetUserInfoResp) InitDefault() {
}

func (p *GetUserInfoResp) GetStatus() (v int64) {
	return p.Status
}

func (p *GetUserInfoResp) GetInfo() (v string) {
	return p.Info
}

var GetUserInfoResp_Data_DEFAULT *RvUserInfo

func (p *GetUserInfoResp) GetData() (v *RvUserInfo) {
	if !p.IsSetData() {
		return GetUserInfoResp_Data_DEFAULT
	}
	return p.Data
}
func (p *GetUserInfoResp) SetStatus(val int64) {
	p.Status = val
}
func (p *GetUserInfoResp) SetInfo(val string) {
	p.Info = val
}
func (p *GetUserInfoResp) SetData(val *RvUserInfo) {
	p.Data = val
}

func (p *GetUserInfoResp) IsSetData() bool {
	return p.Data != nil
}

func (p *GetUserInfoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserInfoResp(%+v)", *p)
}

var fieldIDToName_GetUserInfoResp = map[int16]string{
	1: "status",
	2: "info",
	3: "data",
}

type SetAdminRoleReq struct {
	Uid int64 `thrift:"uid,1,required" frugal:"1,required,i64" json:"uid"`
}

func NewSetAdminRoleReq() *SetAdminRoleReq {
	return &SetAdminRoleReq{}
}

func (p *SetAdminRoleReq) InitDefault() {
}

func (p *SetAdminRoleReq) GetUid() (v int64) {
	return p.Uid
}
func (p *SetAdminRoleReq) SetUid(val int64) {
	p.Uid = val
}

func (p *SetAdminRoleReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SetAdminRoleReq(%+v)", *p)
}

var fieldIDToName_SetAdminRoleReq = map[int16]string{
	1: "uid",
}

type SetAdminRoleResp struct {
	Status int64  `thrift:"status,1,required" frugal:"1,required,i64" json:"status"`
	Info   string `thrift:"info,2,required" frugal:"2,required,string" json:"info"`
}

func NewSetAdminRoleResp() *SetAdminRoleResp {
	return &SetAdminRoleResp{}
}

func (p *SetAdminRoleResp) InitDefault() {
}

func (p *SetAdminRoleResp) GetStatus() (v int64) {
	return p.Status
}

func (p *SetAdminRoleResp) GetInfo() (v string) {
	return p.Info
}
func (p *SetAdminRoleResp) SetStatus(val int64) {
	p.Status = val
}
func (p *SetAdminRoleResp) SetInfo(val string) {
	p.Info = val
}

func (p *SetAdminRoleResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SetAdminRoleResp(%+v)", *p)
}

var fieldIDToName_SetAdminRoleResp = map[int16]string{
	1: "status",
	2: "info",
}

type GetAdminerResp struct {
	Status int64         `thrift:"status,1,required" frugal:"1,required,i64" json:"status"`
	Info   string        `thrift:"info,2,required" frugal:"2,required,string" json:"info"`
	Data   []*RvUserInfo `thrift:"data,3,optional" frugal:"3,optional,list<RvUserInfo>" json:"data,omitempty"`
}

func NewGetAdminerResp() *GetAdminerResp {
	return &GetAdminerResp{}
}

func (p *GetAdminerResp) InitDefault() {
}

func (p *GetAdminerResp) GetStatus() (v int64) {
	return p.Status
}

func (p *GetAdminerResp) GetInfo() (v string) {
	return p.Info
}

var GetAdminerResp_Data_DEFAULT []*RvUserInfo

func (p *GetAdminerResp) GetData() (v []*RvUserInfo) {
	if !p.IsSetData() {
		return GetAdminerResp_Data_DEFAULT
	}
	return p.Data
}
func (p *GetAdminerResp) SetStatus(val int64) {
	p.Status = val
}
func (p *GetAdminerResp) SetInfo(val string) {
	p.Info = val
}
func (p *GetAdminerResp) SetData(val []*RvUserInfo) {
	p.Data = val
}

func (p *GetAdminerResp) IsSetData() bool {
	return p.Data != nil
}

func (p *GetAdminerResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetAdminerResp(%+v)", *p)
}

var fieldIDToName_GetAdminerResp = map[int16]string{
	1: "status",
	2: "info",
	3: "data",
}

type GetUsersResp struct {
	Status int64         `thrift:"status,1,required" frugal:"1,required,i64" json:"status"`
	Info   string        `thrift:"info,2,required" frugal:"2,required,string" json:"info"`
	Data   []*RvUserInfo `thrift:"data,3,optional" frugal:"3,optional,list<RvUserInfo>" json:"data,omitempty"`
}

func NewGetUsersResp() *GetUsersResp {
	return &GetUsersResp{}
}

func (p *GetUsersResp) InitDefault() {
}

func (p *GetUsersResp) GetStatus() (v int64) {
	return p.Status
}

func (p *GetUsersResp) GetInfo() (v string) {
	return p.Info
}

var GetUsersResp_Data_DEFAULT []*RvUserInfo

func (p *GetUsersResp) GetData() (v []*RvUserInfo) {
	if !p.IsSetData() {
		return GetUsersResp_Data_DEFAULT
	}
	return p.Data
}
func (p *GetUsersResp) SetStatus(val int64) {
	p.Status = val
}
func (p *GetUsersResp) SetInfo(val string) {
	p.Info = val
}
func (p *GetUsersResp) SetData(val []*RvUserInfo) {
	p.Data = val
}

func (p *GetUsersResp) IsSetData() bool {
	return p.Data != nil
}

func (p *GetUsersResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUsersResp(%+v)", *p)
}

var fieldIDToName_GetUsersResp = map[int16]string{
	1: "status",
	2: "info",
	3: "data",
}

type LogoutReq struct {
	Uid int64 `thrift:"uid,1,required" frugal:"1,required,i64" json:"uid"`
}

func NewLogoutReq() *LogoutReq {
	return &LogoutReq{}
}

func (p *LogoutReq) InitDefault() {
}

func (p *LogoutReq) GetUid() (v int64) {
	return p.Uid
}
func (p *LogoutReq) SetUid(val int64) {
	p.Uid = val
}

func (p *LogoutReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LogoutReq(%+v)", *p)
}

var fieldIDToName_LogoutReq = map[int16]string{
	1: "uid",
}

type LogoutResp struct {
	Status int64  `thrift:"status,1,required" frugal:"1,required,i64" json:"status"`
	Info   string `thrift:"info,2,required" frugal:"2,required,string" json:"info"`
}

func NewLogoutResp() *LogoutResp {
	return &LogoutResp{}
}

func (p *LogoutResp) InitDefault() {
}

func (p *LogoutResp) GetStatus() (v int64) {
	return p.Status
}

func (p *LogoutResp) GetInfo() (v string) {
	return p.Info
}
func (p *LogoutResp) SetStatus(val int64) {
	p.Status = val
}
func (p *LogoutResp) SetInfo(val string) {
	p.Info = val
}

func (p *LogoutResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LogoutResp(%+v)", *p)
}

var fieldIDToName_LogoutResp = map[int16]string{
	1: "status",
	2: "info",
}

type UserSvr interface {
	UserLogin(ctx context.Context, req *LoginReq) (r *LoginResp, err error)

	RefreshToken(ctx context.Context, req *RefreshReq) (r *RefreshResp, err error)

	GetUserInfo(ctx context.Context, req *GetUserInfoReq) (r *GetUserInfoResp, err error)

	SetAdminRole(ctx context.Context, req *SetAdminRoleReq) (r *SetAdminRoleResp, err error)

	GetAdminer(ctx context.Context) (r *GetAdminerResp, err error)

	GetUsers(ctx context.Context) (r *GetUsersResp, err error)

	Logout(ctx context.Context, req *LogoutReq) (r *LogoutResp, err error)
}

type UserSvrUserLoginArgs struct {
	Req *LoginReq `thrift:"req,1" frugal:"1,default,LoginReq" json:"req"`
}

func NewUserSvrUserLoginArgs() *UserSvrUserLoginArgs {
	return &UserSvrUserLoginArgs{}
}

func (p *UserSvrUserLoginArgs) InitDefault() {
}

var UserSvrUserLoginArgs_Req_DEFAULT *LoginReq

func (p *UserSvrUserLoginArgs) GetReq() (v *LoginReq) {
	if !p.IsSetReq() {
		return UserSvrUserLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserSvrUserLoginArgs) SetReq(val *LoginReq) {
	p.Req = val
}

func (p *UserSvrUserLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserSvrUserLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserSvrUserLoginArgs(%+v)", *p)
}

var fieldIDToName_UserSvrUserLoginArgs = map[int16]string{
	1: "req",
}

type UserSvrUserLoginResult struct {
	Success *LoginResp `thrift:"success,0,optional" frugal:"0,optional,LoginResp" json:"success,omitempty"`
}

func NewUserSvrUserLoginResult() *UserSvrUserLoginResult {
	return &UserSvrUserLoginResult{}
}

func (p *UserSvrUserLoginResult) InitDefault() {
}

var UserSvrUserLoginResult_Success_DEFAULT *LoginResp

func (p *UserSvrUserLoginResult) GetSuccess() (v *LoginResp) {
	if !p.IsSetSuccess() {
		return UserSvrUserLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserSvrUserLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*LoginResp)
}

func (p *UserSvrUserLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserSvrUserLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserSvrUserLoginResult(%+v)", *p)
}

var fieldIDToName_UserSvrUserLoginResult = map[int16]string{
	0: "success",
}

type UserSvrRefreshTokenArgs struct {
	Req *RefreshReq `thrift:"req,1" frugal:"1,default,RefreshReq" json:"req"`
}

func NewUserSvrRefreshTokenArgs() *UserSvrRefreshTokenArgs {
	return &UserSvrRefreshTokenArgs{}
}

func (p *UserSvrRefreshTokenArgs) InitDefault() {
}

var UserSvrRefreshTokenArgs_Req_DEFAULT *RefreshReq

func (p *UserSvrRefreshTokenArgs) GetReq() (v *RefreshReq) {
	if !p.IsSetReq() {
		return UserSvrRefreshTokenArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserSvrRefreshTokenArgs) SetReq(val *RefreshReq) {
	p.Req = val
}

func (p *UserSvrRefreshTokenArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserSvrRefreshTokenArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserSvrRefreshTokenArgs(%+v)", *p)
}

var fieldIDToName_UserSvrRefreshTokenArgs = map[int16]string{
	1: "req",
}

type UserSvrRefreshTokenResult struct {
	Success *RefreshResp `thrift:"success,0,optional" frugal:"0,optional,RefreshResp" json:"success,omitempty"`
}

func NewUserSvrRefreshTokenResult() *UserSvrRefreshTokenResult {
	return &UserSvrRefreshTokenResult{}
}

func (p *UserSvrRefreshTokenResult) InitDefault() {
}

var UserSvrRefreshTokenResult_Success_DEFAULT *RefreshResp

func (p *UserSvrRefreshTokenResult) GetSuccess() (v *RefreshResp) {
	if !p.IsSetSuccess() {
		return UserSvrRefreshTokenResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserSvrRefreshTokenResult) SetSuccess(x interface{}) {
	p.Success = x.(*RefreshResp)
}

func (p *UserSvrRefreshTokenResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserSvrRefreshTokenResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserSvrRefreshTokenResult(%+v)", *p)
}

var fieldIDToName_UserSvrRefreshTokenResult = map[int16]string{
	0: "success",
}

type UserSvrGetUserInfoArgs struct {
	Req *GetUserInfoReq `thrift:"req,1" frugal:"1,default,GetUserInfoReq" json:"req"`
}

func NewUserSvrGetUserInfoArgs() *UserSvrGetUserInfoArgs {
	return &UserSvrGetUserInfoArgs{}
}

func (p *UserSvrGetUserInfoArgs) InitDefault() {
}

var UserSvrGetUserInfoArgs_Req_DEFAULT *GetUserInfoReq

func (p *UserSvrGetUserInfoArgs) GetReq() (v *GetUserInfoReq) {
	if !p.IsSetReq() {
		return UserSvrGetUserInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserSvrGetUserInfoArgs) SetReq(val *GetUserInfoReq) {
	p.Req = val
}

func (p *UserSvrGetUserInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserSvrGetUserInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserSvrGetUserInfoArgs(%+v)", *p)
}

var fieldIDToName_UserSvrGetUserInfoArgs = map[int16]string{
	1: "req",
}

type UserSvrGetUserInfoResult struct {
	Success *GetUserInfoResp `thrift:"success,0,optional" frugal:"0,optional,GetUserInfoResp" json:"success,omitempty"`
}

func NewUserSvrGetUserInfoResult() *UserSvrGetUserInfoResult {
	return &UserSvrGetUserInfoResult{}
}

func (p *UserSvrGetUserInfoResult) InitDefault() {
}

var UserSvrGetUserInfoResult_Success_DEFAULT *GetUserInfoResp

func (p *UserSvrGetUserInfoResult) GetSuccess() (v *GetUserInfoResp) {
	if !p.IsSetSuccess() {
		return UserSvrGetUserInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserSvrGetUserInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUserInfoResp)
}

func (p *UserSvrGetUserInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserSvrGetUserInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserSvrGetUserInfoResult(%+v)", *p)
}

var fieldIDToName_UserSvrGetUserInfoResult = map[int16]string{
	0: "success",
}

type UserSvrSetAdminRoleArgs struct {
	Req *SetAdminRoleReq `thrift:"req,1" frugal:"1,default,SetAdminRoleReq" json:"req"`
}

func NewUserSvrSetAdminRoleArgs() *UserSvrSetAdminRoleArgs {
	return &UserSvrSetAdminRoleArgs{}
}

func (p *UserSvrSetAdminRoleArgs) InitDefault() {
}

var UserSvrSetAdminRoleArgs_Req_DEFAULT *SetAdminRoleReq

func (p *UserSvrSetAdminRoleArgs) GetReq() (v *SetAdminRoleReq) {
	if !p.IsSetReq() {
		return UserSvrSetAdminRoleArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserSvrSetAdminRoleArgs) SetReq(val *SetAdminRoleReq) {
	p.Req = val
}

func (p *UserSvrSetAdminRoleArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserSvrSetAdminRoleArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserSvrSetAdminRoleArgs(%+v)", *p)
}

var fieldIDToName_UserSvrSetAdminRoleArgs = map[int16]string{
	1: "req",
}

type UserSvrSetAdminRoleResult struct {
	Success *SetAdminRoleResp `thrift:"success,0,optional" frugal:"0,optional,SetAdminRoleResp" json:"success,omitempty"`
}

func NewUserSvrSetAdminRoleResult() *UserSvrSetAdminRoleResult {
	return &UserSvrSetAdminRoleResult{}
}

func (p *UserSvrSetAdminRoleResult) InitDefault() {
}

var UserSvrSetAdminRoleResult_Success_DEFAULT *SetAdminRoleResp

func (p *UserSvrSetAdminRoleResult) GetSuccess() (v *SetAdminRoleResp) {
	if !p.IsSetSuccess() {
		return UserSvrSetAdminRoleResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserSvrSetAdminRoleResult) SetSuccess(x interface{}) {
	p.Success = x.(*SetAdminRoleResp)
}

func (p *UserSvrSetAdminRoleResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserSvrSetAdminRoleResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserSvrSetAdminRoleResult(%+v)", *p)
}

var fieldIDToName_UserSvrSetAdminRoleResult = map[int16]string{
	0: "success",
}

type UserSvrGetAdminerArgs struct {
}

func NewUserSvrGetAdminerArgs() *UserSvrGetAdminerArgs {
	return &UserSvrGetAdminerArgs{}
}

func (p *UserSvrGetAdminerArgs) InitDefault() {
}

func (p *UserSvrGetAdminerArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserSvrGetAdminerArgs(%+v)", *p)
}

var fieldIDToName_UserSvrGetAdminerArgs = map[int16]string{}

type UserSvrGetAdminerResult struct {
	Success *GetAdminerResp `thrift:"success,0,optional" frugal:"0,optional,GetAdminerResp" json:"success,omitempty"`
}

func NewUserSvrGetAdminerResult() *UserSvrGetAdminerResult {
	return &UserSvrGetAdminerResult{}
}

func (p *UserSvrGetAdminerResult) InitDefault() {
}

var UserSvrGetAdminerResult_Success_DEFAULT *GetAdminerResp

func (p *UserSvrGetAdminerResult) GetSuccess() (v *GetAdminerResp) {
	if !p.IsSetSuccess() {
		return UserSvrGetAdminerResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserSvrGetAdminerResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetAdminerResp)
}

func (p *UserSvrGetAdminerResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserSvrGetAdminerResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserSvrGetAdminerResult(%+v)", *p)
}

var fieldIDToName_UserSvrGetAdminerResult = map[int16]string{
	0: "success",
}

type UserSvrGetUsersArgs struct {
}

func NewUserSvrGetUsersArgs() *UserSvrGetUsersArgs {
	return &UserSvrGetUsersArgs{}
}

func (p *UserSvrGetUsersArgs) InitDefault() {
}

func (p *UserSvrGetUsersArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserSvrGetUsersArgs(%+v)", *p)
}

var fieldIDToName_UserSvrGetUsersArgs = map[int16]string{}

type UserSvrGetUsersResult struct {
	Success *GetUsersResp `thrift:"success,0,optional" frugal:"0,optional,GetUsersResp" json:"success,omitempty"`
}

func NewUserSvrGetUsersResult() *UserSvrGetUsersResult {
	return &UserSvrGetUsersResult{}
}

func (p *UserSvrGetUsersResult) InitDefault() {
}

var UserSvrGetUsersResult_Success_DEFAULT *GetUsersResp

func (p *UserSvrGetUsersResult) GetSuccess() (v *GetUsersResp) {
	if !p.IsSetSuccess() {
		return UserSvrGetUsersResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserSvrGetUsersResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUsersResp)
}

func (p *UserSvrGetUsersResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserSvrGetUsersResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserSvrGetUsersResult(%+v)", *p)
}

var fieldIDToName_UserSvrGetUsersResult = map[int16]string{
	0: "success",
}

type UserSvrLogoutArgs struct {
	Req *LogoutReq `thrift:"req,1" frugal:"1,default,LogoutReq" json:"req"`
}

func NewUserSvrLogoutArgs() *UserSvrLogoutArgs {
	return &UserSvrLogoutArgs{}
}

func (p *UserSvrLogoutArgs) InitDefault() {
}

var UserSvrLogoutArgs_Req_DEFAULT *LogoutReq

func (p *UserSvrLogoutArgs) GetReq() (v *LogoutReq) {
	if !p.IsSetReq() {
		return UserSvrLogoutArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserSvrLogoutArgs) SetReq(val *LogoutReq) {
	p.Req = val
}

func (p *UserSvrLogoutArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserSvrLogoutArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserSvrLogoutArgs(%+v)", *p)
}

var fieldIDToName_UserSvrLogoutArgs = map[int16]string{
	1: "req",
}

type UserSvrLogoutResult struct {
	Success *LogoutResp `thrift:"success,0,optional" frugal:"0,optional,LogoutResp" json:"success,omitempty"`
}

func NewUserSvrLogoutResult() *UserSvrLogoutResult {
	return &UserSvrLogoutResult{}
}

func (p *UserSvrLogoutResult) InitDefault() {
}

var UserSvrLogoutResult_Success_DEFAULT *LogoutResp

func (p *UserSvrLogoutResult) GetSuccess() (v *LogoutResp) {
	if !p.IsSetSuccess() {
		return UserSvrLogoutResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserSvrLogoutResult) SetSuccess(x interface{}) {
	p.Success = x.(*LogoutResp)
}

func (p *UserSvrLogoutResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserSvrLogoutResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserSvrLogoutResult(%+v)", *p)
}

var fieldIDToName_UserSvrLogoutResult = map[int16]string{
	0: "success",
}
