// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package livesvr

import (
	"LiveDanmu/apps/rpc/livesvr/kitex_gen/usersvr"
	"context"
	"fmt"
)

type LiveInfo struct {
	Rvid             int64               `thrift:"rvid,1,required" frugal:"1,required,i64" json:"rvid"`
	OwerId           int64               `thrift:"ower_id,2,required" frugal:"2,required,i64" json:"ower_id"`
	Title            string              `thrift:"title,3,required" frugal:"3,required,string" json:"title"`
	StreamName       string              `thrift:"stream_name,4,required" frugal:"4,required,string" json:"stream_name"`
	UpstreamPassword *string             `thrift:"upstream_password,5,optional" frugal:"5,optional,string" json:"upstream_password,omitempty"`
	UserInfo         *usersvr.RvUserInfo `thrift:"user_info,6,optional" frugal:"6,optional,usersvr.RvUserInfo" json:"user_info,omitempty"`
}

func NewLiveInfo() *LiveInfo {
	return &LiveInfo{}
}

func (p *LiveInfo) InitDefault() {
}

func (p *LiveInfo) GetRvid() (v int64) {
	return p.Rvid
}

func (p *LiveInfo) GetOwerId() (v int64) {
	return p.OwerId
}

func (p *LiveInfo) GetTitle() (v string) {
	return p.Title
}

func (p *LiveInfo) GetStreamName() (v string) {
	return p.StreamName
}

var LiveInfo_UpstreamPassword_DEFAULT string

func (p *LiveInfo) GetUpstreamPassword() (v string) {
	if !p.IsSetUpstreamPassword() {
		return LiveInfo_UpstreamPassword_DEFAULT
	}
	return *p.UpstreamPassword
}

var LiveInfo_UserInfo_DEFAULT *usersvr.RvUserInfo

func (p *LiveInfo) GetUserInfo() (v *usersvr.RvUserInfo) {
	if !p.IsSetUserInfo() {
		return LiveInfo_UserInfo_DEFAULT
	}
	return p.UserInfo
}
func (p *LiveInfo) SetRvid(val int64) {
	p.Rvid = val
}
func (p *LiveInfo) SetOwerId(val int64) {
	p.OwerId = val
}
func (p *LiveInfo) SetTitle(val string) {
	p.Title = val
}
func (p *LiveInfo) SetStreamName(val string) {
	p.StreamName = val
}
func (p *LiveInfo) SetUpstreamPassword(val *string) {
	p.UpstreamPassword = val
}
func (p *LiveInfo) SetUserInfo(val *usersvr.RvUserInfo) {
	p.UserInfo = val
}

func (p *LiveInfo) IsSetUpstreamPassword() bool {
	return p.UpstreamPassword != nil
}

func (p *LiveInfo) IsSetUserInfo() bool {
	return p.UserInfo != nil
}

func (p *LiveInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LiveInfo(%+v)", *p)
}

var fieldIDToName_LiveInfo = map[int16]string{
	1: "rvid",
	2: "ower_id",
	3: "title",
	4: "stream_name",
	5: "upstream_password",
	6: "user_info",
}

type GetLiveListData struct {
	Total int64       `thrift:"total,1,required" frugal:"1,required,i64" json:"total"`
	Lives []*LiveInfo `thrift:"lives,2,required" frugal:"2,required,list<LiveInfo>" json:"lives"`
}

func NewGetLiveListData() *GetLiveListData {
	return &GetLiveListData{}
}

func (p *GetLiveListData) InitDefault() {
}

func (p *GetLiveListData) GetTotal() (v int64) {
	return p.Total
}

func (p *GetLiveListData) GetLives() (v []*LiveInfo) {
	return p.Lives
}
func (p *GetLiveListData) SetTotal(val int64) {
	p.Total = val
}
func (p *GetLiveListData) SetLives(val []*LiveInfo) {
	p.Lives = val
}

func (p *GetLiveListData) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetLiveListData(%+v)", *p)
}

var fieldIDToName_GetLiveListData = map[int16]string{
	1: "total",
	2: "lives",
}

type GetLiveInfoReq struct {
	Rvid int64 `thrift:"rvid,1,required" frugal:"1,required,i64" json:"rvid"`
	Uid  int64 `thrift:"uid,2,required" frugal:"2,required,i64" json:"uid"`
}

func NewGetLiveInfoReq() *GetLiveInfoReq {
	return &GetLiveInfoReq{}
}

func (p *GetLiveInfoReq) InitDefault() {
}

func (p *GetLiveInfoReq) GetRvid() (v int64) {
	return p.Rvid
}

func (p *GetLiveInfoReq) GetUid() (v int64) {
	return p.Uid
}
func (p *GetLiveInfoReq) SetRvid(val int64) {
	p.Rvid = val
}
func (p *GetLiveInfoReq) SetUid(val int64) {
	p.Uid = val
}

func (p *GetLiveInfoReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetLiveInfoReq(%+v)", *p)
}

var fieldIDToName_GetLiveInfoReq = map[int16]string{
	1: "rvid",
	2: "uid",
}

type GetLiveInfoResp struct {
	Status int64     `thrift:"status,1,required" frugal:"1,required,i64" json:"status"`
	Info   string    `thrift:"info,2,required" frugal:"2,required,string" json:"info"`
	Data   *LiveInfo `thrift:"data,3,optional" frugal:"3,optional,LiveInfo" json:"data,omitempty"`
}

func NewGetLiveInfoResp() *GetLiveInfoResp {
	return &GetLiveInfoResp{}
}

func (p *GetLiveInfoResp) InitDefault() {
}

func (p *GetLiveInfoResp) GetStatus() (v int64) {
	return p.Status
}

func (p *GetLiveInfoResp) GetInfo() (v string) {
	return p.Info
}

var GetLiveInfoResp_Data_DEFAULT *LiveInfo

func (p *GetLiveInfoResp) GetData() (v *LiveInfo) {
	if !p.IsSetData() {
		return GetLiveInfoResp_Data_DEFAULT
	}
	return p.Data
}
func (p *GetLiveInfoResp) SetStatus(val int64) {
	p.Status = val
}
func (p *GetLiveInfoResp) SetInfo(val string) {
	p.Info = val
}
func (p *GetLiveInfoResp) SetData(val *LiveInfo) {
	p.Data = val
}

func (p *GetLiveInfoResp) IsSetData() bool {
	return p.Data != nil
}

func (p *GetLiveInfoResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetLiveInfoResp(%+v)", *p)
}

var fieldIDToName_GetLiveInfoResp = map[int16]string{
	1: "status",
	2: "info",
	3: "data",
}

type GetLiveListReq struct {
	Page     int32 `thrift:"page,1,required" frugal:"1,required,i32" json:"page"`
	PageSize int32 `thrift:"pageSize,2,required" frugal:"2,required,i32" json:"pageSize"`
}

func NewGetLiveListReq() *GetLiveListReq {
	return &GetLiveListReq{}
}

func (p *GetLiveListReq) InitDefault() {
}

func (p *GetLiveListReq) GetPage() (v int32) {
	return p.Page
}

func (p *GetLiveListReq) GetPageSize() (v int32) {
	return p.PageSize
}
func (p *GetLiveListReq) SetPage(val int32) {
	p.Page = val
}
func (p *GetLiveListReq) SetPageSize(val int32) {
	p.PageSize = val
}

func (p *GetLiveListReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetLiveListReq(%+v)", *p)
}

var fieldIDToName_GetLiveListReq = map[int16]string{
	1: "page",
	2: "pageSize",
}

type GetLiveListResp struct {
	Status int64            `thrift:"status,1,required" frugal:"1,required,i64" json:"status"`
	Info   string           `thrift:"info,2,required" frugal:"2,required,string" json:"info"`
	Data   *GetLiveListData `thrift:"data,3,optional" frugal:"3,optional,GetLiveListData" json:"data,omitempty"`
}

func NewGetLiveListResp() *GetLiveListResp {
	return &GetLiveListResp{}
}

func (p *GetLiveListResp) InitDefault() {
}

func (p *GetLiveListResp) GetStatus() (v int64) {
	return p.Status
}

func (p *GetLiveListResp) GetInfo() (v string) {
	return p.Info
}

var GetLiveListResp_Data_DEFAULT *GetLiveListData

func (p *GetLiveListResp) GetData() (v *GetLiveListData) {
	if !p.IsSetData() {
		return GetLiveListResp_Data_DEFAULT
	}
	return p.Data
}
func (p *GetLiveListResp) SetStatus(val int64) {
	p.Status = val
}
func (p *GetLiveListResp) SetInfo(val string) {
	p.Info = val
}
func (p *GetLiveListResp) SetData(val *GetLiveListData) {
	p.Data = val
}

func (p *GetLiveListResp) IsSetData() bool {
	return p.Data != nil
}

func (p *GetLiveListResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetLiveListResp(%+v)", *p)
}

var fieldIDToName_GetLiveListResp = map[int16]string{
	1: "status",
	2: "info",
	3: "data",
}

type StartLiveReq struct {
	OwerId int64  `thrift:"ower_id,1,required" frugal:"1,required,i64" json:"ower_id"`
	Title  string `thrift:"title,2,required" frugal:"2,required,string" json:"title"`
}

func NewStartLiveReq() *StartLiveReq {
	return &StartLiveReq{}
}

func (p *StartLiveReq) InitDefault() {
}

func (p *StartLiveReq) GetOwerId() (v int64) {
	return p.OwerId
}

func (p *StartLiveReq) GetTitle() (v string) {
	return p.Title
}
func (p *StartLiveReq) SetOwerId(val int64) {
	p.OwerId = val
}
func (p *StartLiveReq) SetTitle(val string) {
	p.Title = val
}

func (p *StartLiveReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StartLiveReq(%+v)", *p)
}

var fieldIDToName_StartLiveReq = map[int16]string{
	1: "ower_id",
	2: "title",
}

type StartLiveResp struct {
	Status int64     `thrift:"status,1,required" frugal:"1,required,i64" json:"status"`
	Info   string    `thrift:"info,2,required" frugal:"2,required,string" json:"info"`
	Data   *LiveInfo `thrift:"data,3,optional" frugal:"3,optional,LiveInfo" json:"data,omitempty"`
}

func NewStartLiveResp() *StartLiveResp {
	return &StartLiveResp{}
}

func (p *StartLiveResp) InitDefault() {
}

func (p *StartLiveResp) GetStatus() (v int64) {
	return p.Status
}

func (p *StartLiveResp) GetInfo() (v string) {
	return p.Info
}

var StartLiveResp_Data_DEFAULT *LiveInfo

func (p *StartLiveResp) GetData() (v *LiveInfo) {
	if !p.IsSetData() {
		return StartLiveResp_Data_DEFAULT
	}
	return p.Data
}
func (p *StartLiveResp) SetStatus(val int64) {
	p.Status = val
}
func (p *StartLiveResp) SetInfo(val string) {
	p.Info = val
}
func (p *StartLiveResp) SetData(val *LiveInfo) {
	p.Data = val
}

func (p *StartLiveResp) IsSetData() bool {
	return p.Data != nil
}

func (p *StartLiveResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StartLiveResp(%+v)", *p)
}

var fieldIDToName_StartLiveResp = map[int16]string{
	1: "status",
	2: "info",
	3: "data",
}

type StopLiveReq struct {
	Rvid int64 `thrift:"rvid,1,required" frugal:"1,required,i64" json:"rvid"`
	Uid  int64 `thrift:"uid,2,required" frugal:"2,required,i64" json:"uid"`
}

func NewStopLiveReq() *StopLiveReq {
	return &StopLiveReq{}
}

func (p *StopLiveReq) InitDefault() {
}

func (p *StopLiveReq) GetRvid() (v int64) {
	return p.Rvid
}

func (p *StopLiveReq) GetUid() (v int64) {
	return p.Uid
}
func (p *StopLiveReq) SetRvid(val int64) {
	p.Rvid = val
}
func (p *StopLiveReq) SetUid(val int64) {
	p.Uid = val
}

func (p *StopLiveReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StopLiveReq(%+v)", *p)
}

var fieldIDToName_StopLiveReq = map[int16]string{
	1: "rvid",
	2: "uid",
}

type StopLiveResp struct {
	Status int64  `thrift:"status,1,required" frugal:"1,required,i64" json:"status"`
	Info   string `thrift:"info,2,required" frugal:"2,required,string" json:"info"`
}

func NewStopLiveResp() *StopLiveResp {
	return &StopLiveResp{}
}

func (p *StopLiveResp) InitDefault() {
}

func (p *StopLiveResp) GetStatus() (v int64) {
	return p.Status
}

func (p *StopLiveResp) GetInfo() (v string) {
	return p.Info
}
func (p *StopLiveResp) SetStatus(val int64) {
	p.Status = val
}
func (p *StopLiveResp) SetInfo(val string) {
	p.Info = val
}

func (p *StopLiveResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("StopLiveResp(%+v)", *p)
}

var fieldIDToName_StopLiveResp = map[int16]string{
	1: "status",
	2: "info",
}

type SRSAuthReq struct {
	Rvid     int64  `thrift:"rvid,1,required" frugal:"1,required,i64" json:"rvid"`
	Password string `thrift:"password,2,required" frugal:"2,required,string" json:"password"`
}

func NewSRSAuthReq() *SRSAuthReq {
	return &SRSAuthReq{}
}

func (p *SRSAuthReq) InitDefault() {
}

func (p *SRSAuthReq) GetRvid() (v int64) {
	return p.Rvid
}

func (p *SRSAuthReq) GetPassword() (v string) {
	return p.Password
}
func (p *SRSAuthReq) SetRvid(val int64) {
	p.Rvid = val
}
func (p *SRSAuthReq) SetPassword(val string) {
	p.Password = val
}

func (p *SRSAuthReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SRSAuthReq(%+v)", *p)
}

var fieldIDToName_SRSAuthReq = map[int16]string{
	1: "rvid",
	2: "password",
}

type SRSAuthResp struct {
	Ok int32 `thrift:"ok,1,required" frugal:"1,required,i32" json:"ok"`
}

func NewSRSAuthResp() *SRSAuthResp {
	return &SRSAuthResp{
		Ok: 1,
	}
}

func (p *SRSAuthResp) InitDefault() {
	p.Ok = 1
}

func (p *SRSAuthResp) GetOk() (v int32) {
	return p.Ok
}
func (p *SRSAuthResp) SetOk(val int32) {
	p.Ok = val
}

func (p *SRSAuthResp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SRSAuthResp(%+v)", *p)
}

var fieldIDToName_SRSAuthResp = map[int16]string{
	1: "ok",
}

type LiveSvr interface {
	GetLiveInfo(ctx context.Context, req *GetLiveInfoReq) (r *GetLiveInfoResp, err error)

	GetLiveList(ctx context.Context, req *GetLiveListReq) (r *GetLiveListResp, err error)

	StartLive(ctx context.Context, req *StartLiveReq) (r *StartLiveResp, err error)

	StopLive(ctx context.Context, req *StopLiveReq) (r *StopLiveResp, err error)

	SRSAuth(ctx context.Context, req *SRSAuthReq) (r *SRSAuthResp, err error)
}

type LiveSvrGetLiveInfoArgs struct {
	Req *GetLiveInfoReq `thrift:"req,1" frugal:"1,default,GetLiveInfoReq" json:"req"`
}

func NewLiveSvrGetLiveInfoArgs() *LiveSvrGetLiveInfoArgs {
	return &LiveSvrGetLiveInfoArgs{}
}

func (p *LiveSvrGetLiveInfoArgs) InitDefault() {
}

var LiveSvrGetLiveInfoArgs_Req_DEFAULT *GetLiveInfoReq

func (p *LiveSvrGetLiveInfoArgs) GetReq() (v *GetLiveInfoReq) {
	if !p.IsSetReq() {
		return LiveSvrGetLiveInfoArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *LiveSvrGetLiveInfoArgs) SetReq(val *GetLiveInfoReq) {
	p.Req = val
}

func (p *LiveSvrGetLiveInfoArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LiveSvrGetLiveInfoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LiveSvrGetLiveInfoArgs(%+v)", *p)
}

var fieldIDToName_LiveSvrGetLiveInfoArgs = map[int16]string{
	1: "req",
}

type LiveSvrGetLiveInfoResult struct {
	Success *GetLiveInfoResp `thrift:"success,0,optional" frugal:"0,optional,GetLiveInfoResp" json:"success,omitempty"`
}

func NewLiveSvrGetLiveInfoResult() *LiveSvrGetLiveInfoResult {
	return &LiveSvrGetLiveInfoResult{}
}

func (p *LiveSvrGetLiveInfoResult) InitDefault() {
}

var LiveSvrGetLiveInfoResult_Success_DEFAULT *GetLiveInfoResp

func (p *LiveSvrGetLiveInfoResult) GetSuccess() (v *GetLiveInfoResp) {
	if !p.IsSetSuccess() {
		return LiveSvrGetLiveInfoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *LiveSvrGetLiveInfoResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetLiveInfoResp)
}

func (p *LiveSvrGetLiveInfoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LiveSvrGetLiveInfoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LiveSvrGetLiveInfoResult(%+v)", *p)
}

var fieldIDToName_LiveSvrGetLiveInfoResult = map[int16]string{
	0: "success",
}

type LiveSvrGetLiveListArgs struct {
	Req *GetLiveListReq `thrift:"req,1" frugal:"1,default,GetLiveListReq" json:"req"`
}

func NewLiveSvrGetLiveListArgs() *LiveSvrGetLiveListArgs {
	return &LiveSvrGetLiveListArgs{}
}

func (p *LiveSvrGetLiveListArgs) InitDefault() {
}

var LiveSvrGetLiveListArgs_Req_DEFAULT *GetLiveListReq

func (p *LiveSvrGetLiveListArgs) GetReq() (v *GetLiveListReq) {
	if !p.IsSetReq() {
		return LiveSvrGetLiveListArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *LiveSvrGetLiveListArgs) SetReq(val *GetLiveListReq) {
	p.Req = val
}

func (p *LiveSvrGetLiveListArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LiveSvrGetLiveListArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LiveSvrGetLiveListArgs(%+v)", *p)
}

var fieldIDToName_LiveSvrGetLiveListArgs = map[int16]string{
	1: "req",
}

type LiveSvrGetLiveListResult struct {
	Success *GetLiveListResp `thrift:"success,0,optional" frugal:"0,optional,GetLiveListResp" json:"success,omitempty"`
}

func NewLiveSvrGetLiveListResult() *LiveSvrGetLiveListResult {
	return &LiveSvrGetLiveListResult{}
}

func (p *LiveSvrGetLiveListResult) InitDefault() {
}

var LiveSvrGetLiveListResult_Success_DEFAULT *GetLiveListResp

func (p *LiveSvrGetLiveListResult) GetSuccess() (v *GetLiveListResp) {
	if !p.IsSetSuccess() {
		return LiveSvrGetLiveListResult_Success_DEFAULT
	}
	return p.Success
}
func (p *LiveSvrGetLiveListResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetLiveListResp)
}

func (p *LiveSvrGetLiveListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LiveSvrGetLiveListResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LiveSvrGetLiveListResult(%+v)", *p)
}

var fieldIDToName_LiveSvrGetLiveListResult = map[int16]string{
	0: "success",
}

type LiveSvrStartLiveArgs struct {
	Req *StartLiveReq `thrift:"req,1" frugal:"1,default,StartLiveReq" json:"req"`
}

func NewLiveSvrStartLiveArgs() *LiveSvrStartLiveArgs {
	return &LiveSvrStartLiveArgs{}
}

func (p *LiveSvrStartLiveArgs) InitDefault() {
}

var LiveSvrStartLiveArgs_Req_DEFAULT *StartLiveReq

func (p *LiveSvrStartLiveArgs) GetReq() (v *StartLiveReq) {
	if !p.IsSetReq() {
		return LiveSvrStartLiveArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *LiveSvrStartLiveArgs) SetReq(val *StartLiveReq) {
	p.Req = val
}

func (p *LiveSvrStartLiveArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LiveSvrStartLiveArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LiveSvrStartLiveArgs(%+v)", *p)
}

var fieldIDToName_LiveSvrStartLiveArgs = map[int16]string{
	1: "req",
}

type LiveSvrStartLiveResult struct {
	Success *StartLiveResp `thrift:"success,0,optional" frugal:"0,optional,StartLiveResp" json:"success,omitempty"`
}

func NewLiveSvrStartLiveResult() *LiveSvrStartLiveResult {
	return &LiveSvrStartLiveResult{}
}

func (p *LiveSvrStartLiveResult) InitDefault() {
}

var LiveSvrStartLiveResult_Success_DEFAULT *StartLiveResp

func (p *LiveSvrStartLiveResult) GetSuccess() (v *StartLiveResp) {
	if !p.IsSetSuccess() {
		return LiveSvrStartLiveResult_Success_DEFAULT
	}
	return p.Success
}
func (p *LiveSvrStartLiveResult) SetSuccess(x interface{}) {
	p.Success = x.(*StartLiveResp)
}

func (p *LiveSvrStartLiveResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LiveSvrStartLiveResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LiveSvrStartLiveResult(%+v)", *p)
}

var fieldIDToName_LiveSvrStartLiveResult = map[int16]string{
	0: "success",
}

type LiveSvrStopLiveArgs struct {
	Req *StopLiveReq `thrift:"req,1" frugal:"1,default,StopLiveReq" json:"req"`
}

func NewLiveSvrStopLiveArgs() *LiveSvrStopLiveArgs {
	return &LiveSvrStopLiveArgs{}
}

func (p *LiveSvrStopLiveArgs) InitDefault() {
}

var LiveSvrStopLiveArgs_Req_DEFAULT *StopLiveReq

func (p *LiveSvrStopLiveArgs) GetReq() (v *StopLiveReq) {
	if !p.IsSetReq() {
		return LiveSvrStopLiveArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *LiveSvrStopLiveArgs) SetReq(val *StopLiveReq) {
	p.Req = val
}

func (p *LiveSvrStopLiveArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LiveSvrStopLiveArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LiveSvrStopLiveArgs(%+v)", *p)
}

var fieldIDToName_LiveSvrStopLiveArgs = map[int16]string{
	1: "req",
}

type LiveSvrStopLiveResult struct {
	Success *StopLiveResp `thrift:"success,0,optional" frugal:"0,optional,StopLiveResp" json:"success,omitempty"`
}

func NewLiveSvrStopLiveResult() *LiveSvrStopLiveResult {
	return &LiveSvrStopLiveResult{}
}

func (p *LiveSvrStopLiveResult) InitDefault() {
}

var LiveSvrStopLiveResult_Success_DEFAULT *StopLiveResp

func (p *LiveSvrStopLiveResult) GetSuccess() (v *StopLiveResp) {
	if !p.IsSetSuccess() {
		return LiveSvrStopLiveResult_Success_DEFAULT
	}
	return p.Success
}
func (p *LiveSvrStopLiveResult) SetSuccess(x interface{}) {
	p.Success = x.(*StopLiveResp)
}

func (p *LiveSvrStopLiveResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LiveSvrStopLiveResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LiveSvrStopLiveResult(%+v)", *p)
}

var fieldIDToName_LiveSvrStopLiveResult = map[int16]string{
	0: "success",
}

type LiveSvrSRSAuthArgs struct {
	Req *SRSAuthReq `thrift:"req,1" frugal:"1,default,SRSAuthReq" json:"req"`
}

func NewLiveSvrSRSAuthArgs() *LiveSvrSRSAuthArgs {
	return &LiveSvrSRSAuthArgs{}
}

func (p *LiveSvrSRSAuthArgs) InitDefault() {
}

var LiveSvrSRSAuthArgs_Req_DEFAULT *SRSAuthReq

func (p *LiveSvrSRSAuthArgs) GetReq() (v *SRSAuthReq) {
	if !p.IsSetReq() {
		return LiveSvrSRSAuthArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *LiveSvrSRSAuthArgs) SetReq(val *SRSAuthReq) {
	p.Req = val
}

func (p *LiveSvrSRSAuthArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *LiveSvrSRSAuthArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LiveSvrSRSAuthArgs(%+v)", *p)
}

var fieldIDToName_LiveSvrSRSAuthArgs = map[int16]string{
	1: "req",
}

type LiveSvrSRSAuthResult struct {
	Success *SRSAuthResp `thrift:"success,0,optional" frugal:"0,optional,SRSAuthResp" json:"success,omitempty"`
}

func NewLiveSvrSRSAuthResult() *LiveSvrSRSAuthResult {
	return &LiveSvrSRSAuthResult{}
}

func (p *LiveSvrSRSAuthResult) InitDefault() {
}

var LiveSvrSRSAuthResult_Success_DEFAULT *SRSAuthResp

func (p *LiveSvrSRSAuthResult) GetSuccess() (v *SRSAuthResp) {
	if !p.IsSetSuccess() {
		return LiveSvrSRSAuthResult_Success_DEFAULT
	}
	return p.Success
}
func (p *LiveSvrSRSAuthResult) SetSuccess(x interface{}) {
	p.Success = x.(*SRSAuthResp)
}

func (p *LiveSvrSRSAuthResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *LiveSvrSRSAuthResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LiveSvrSRSAuthResult(%+v)", *p)
}

var fieldIDToName_LiveSvrSRSAuthResult = map[int16]string{
	0: "success",
}
